/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.apollo.openapi.server.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "Portal Management", description = "Portal UI 登录态管理接口，主要供当前版本 Portal 前端调用")
public interface PortalManagementApi {

    default PortalManagementApiDelegate getDelegate() {
        return new PortalManagementApiDelegate() {};
    }

    /**
     * POST /openapi/v1/favorites : 添加收藏(new added)
     * POST /openapi/v1/favorites
     *
     * @param body  (required)
     * @return 成功添加收藏 (status code 200)
     */
    @Operation(
        operationId = "addFavorite",
        summary = "添加收藏(new added)",
        description = "POST /openapi/v1/favorites",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功添加收藏", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/openapi/v1/favorites",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Object> addFavorite(
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body
    ) {
        return getDelegate().addFavorite(body);
    }


    /**
     * POST /openapi/v1/consumers/{token}/assign-role : 给消费者授权(new added)
     * POST /openapi/v1/consumers/{token}/assign-role
     *
     * @param token  (required)
     * @param type  (required)
     * @param body  (required)
     * @param envs  (optional)
     * @return 成功授权 (status code 200)
     */
    @Operation(
        operationId = "assignRoleToConsumer",
        summary = "给消费者授权(new added)",
        description = "POST /openapi/v1/consumers/{token}/assign-role",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功授权", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/openapi/v1/consumers/{token}/assign-role",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<List<Object>> assignRoleToConsumer(
        @Parameter(name = "token", description = "", required = true, in = ParameterIn.PATH) @PathVariable("token") String token,
        @NotNull @Parameter(name = "type", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "type", required = true) String type,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body,
        @Parameter(name = "envs", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "envs", required = false) String envs
    ) {
        return getDelegate().assignRoleToConsumer(token, type, body, envs);
    }


    /**
     * HEAD /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export : 检查应用配置导出权限(new added)
     * HEAD /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export
     *
     * @param appId  (required)
     * @param env  (required)
     * @param clusterName  (required)
     * @return 可导出 (status code 200)
     */
    @Operation(
        operationId = "checkExportAppConfig",
        summary = "检查应用配置导出权限(new added)",
        description = "HEAD /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "可导出")
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.HEAD,
        value = "/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export"
    )
    default ResponseEntity<Void> checkExportAppConfig(
        @Parameter(name = "appId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("appId") String appId,
        @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH) @PathVariable("env") String env,
        @Parameter(name = "clusterName", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clusterName") String clusterName
    ) {
        return getDelegate().checkExportAppConfig(appId, env, clusterName);
    }


    /**
     * GET /openapi/v1/system-info/health : 检查系统实例健康状态(new added)
     * GET /openapi/v1/system-info/health
     *
     * @param instanceId  (required)
     * @return 成功获取健康状态 (status code 200)
     */
    @Operation(
        operationId = "checkSystemHealth",
        summary = "检查系统实例健康状态(new added)",
        description = "GET /openapi/v1/system-info/health",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取健康状态", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/system-info/health",
        produces = { "application/json" }
    )
    default ResponseEntity<Object> checkSystemHealth(
        @NotNull @Parameter(name = "instanceId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "instanceId", required = true) String instanceId
    ) {
        return getDelegate().checkSystemHealth(instanceId);
    }


    /**
     * POST /openapi/v1/consumers : 创建开放平台消费者(new added)
     * POST /openapi/v1/consumers
     *
     * @param body  (required)
     * @param expires  (optional)
     * @return 成功创建消费者 (status code 200)
     */
    @Operation(
        operationId = "createConsumer",
        summary = "创建开放平台消费者(new added)",
        description = "POST /openapi/v1/consumers",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功创建消费者", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/openapi/v1/consumers",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Object> createConsumer(
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body,
        @Parameter(name = "expires", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "expires", required = false) String expires
    ) {
        return getDelegate().createConsumer(body, expires);
    }


    /**
     * POST /openapi/v1/server/envs/{env}/config-db/config : 创建或更新Config DB配置(new added)
     * POST /openapi/v1/server/envs/{env}/config-db/config
     *
     * @param env  (required)
     * @param body  (required)
     * @return 成功创建或更新配置 (status code 200)
     */
    @Operation(
        operationId = "createOrUpdateConfigDBConfig",
        summary = "创建或更新Config DB配置(new added)",
        description = "POST /openapi/v1/server/envs/{env}/config-db/config",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功创建或更新配置", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/openapi/v1/server/envs/{env}/config-db/config",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Object> createOrUpdateConfigDBConfig(
        @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH) @PathVariable("env") String env,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body
    ) {
        return getDelegate().createOrUpdateConfigDBConfig(env, body);
    }


    /**
     * POST /openapi/v1/server/portal-db/config : 创建或更新Portal DB配置(new added)
     * POST /openapi/v1/server/portal-db/config
     *
     * @param body  (required)
     * @return 成功创建或更新配置 (status code 200)
     */
    @Operation(
        operationId = "createOrUpdatePortalDBConfig",
        summary = "创建或更新Portal DB配置(new added)",
        description = "POST /openapi/v1/server/portal-db/config",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功创建或更新配置", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/openapi/v1/server/portal-db/config",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Object> createOrUpdatePortalDBConfig(
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody Object body
    ) {
        return getDelegate().createOrUpdatePortalDBConfig(body);
    }


    /**
     * DELETE /openapi/v1/server/envs/{env}/config-db/config : 删除Config DB配置(new added)
     * DELETE /openapi/v1/server/envs/{env}/config-db/config
     *
     * @param env  (required)
     * @param key  (required)
     * @param cluster  (required)
     * @return 成功删除配置 (status code 200)
     */
    @Operation(
        operationId = "deleteConfigDBConfig",
        summary = "删除Config DB配置(new added)",
        description = "DELETE /openapi/v1/server/envs/{env}/config-db/config",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功删除配置")
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/openapi/v1/server/envs/{env}/config-db/config"
    )
    default ResponseEntity<Void> deleteConfigDBConfig(
        @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH) @PathVariable("env") String env,
        @NotNull @Parameter(name = "key", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "key", required = true) String key,
        @NotNull @Parameter(name = "cluster", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "cluster", required = true) String cluster
    ) {
        return getDelegate().deleteConfigDBConfig(env, key, cluster);
    }


    /**
     * DELETE /openapi/v1/consumers/by-appId : 按应用ID删除消费者(new added)
     * DELETE /openapi/v1/consumers/by-appId
     *
     * @param appId  (required)
     * @return 成功删除消费者 (status code 200)
     */
    @Operation(
        operationId = "deleteConsumer",
        summary = "按应用ID删除消费者(new added)",
        description = "DELETE /openapi/v1/consumers/by-appId",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功删除消费者")
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/openapi/v1/consumers/by-appId"
    )
    default ResponseEntity<Void> deleteConsumer(
        @NotNull @Parameter(name = "appId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "appId", required = true) String appId
    ) {
        return getDelegate().deleteConsumer(appId);
    }


    /**
     * DELETE /openapi/v1/favorites/{favoriteId} : 删除收藏(new added)
     * DELETE /openapi/v1/favorites/{favoriteId}
     *
     * @param favoriteId  (required)
     * @return 成功删除收藏 (status code 200)
     */
    @Operation(
        operationId = "deleteFavorite",
        summary = "删除收藏(new added)",
        description = "DELETE /openapi/v1/favorites/{favoriteId}",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功删除收藏")
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/openapi/v1/favorites/{favoriteId}"
    )
    default ResponseEntity<Void> deleteFavorite(
        @Parameter(name = "favoriteId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("favoriteId") Long favoriteId
    ) {
        return getDelegate().deleteFavorite(favoriteId);
    }


    /**
     * DELETE /openapi/v1/server/portal-db/config : 删除Portal DB配置(new added)
     * DELETE /openapi/v1/server/portal-db/config
     *
     * @param key  (required)
     * @return 成功删除配置 (status code 200)
     */
    @Operation(
        operationId = "deletePortalDBConfig",
        summary = "删除Portal DB配置(new added)",
        description = "DELETE /openapi/v1/server/portal-db/config",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功删除配置")
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/openapi/v1/server/portal-db/config"
    )
    default ResponseEntity<Void> deletePortalDBConfig(
        @NotNull @Parameter(name = "key", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "key", required = true) String key
    ) {
        return getDelegate().deletePortalDBConfig(key);
    }


    /**
     * GET /openapi/v1/configs/export : 导出所有配置(new added)
     * GET /openapi/v1/configs/export
     *
     * @param envs  (required)
     * @return 成功导出配置 (status code 200)
     */
    @Operation(
        operationId = "exportAllConfigs",
        summary = "导出所有配置(new added)",
        description = "GET /openapi/v1/configs/export",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功导出配置", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/configs/export",
        produces = { "application/octet-stream" }
    )
    default ResponseEntity<org.springframework.core.io.Resource> exportAllConfigs(
        @NotNull @Parameter(name = "envs", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "envs", required = true) String envs
    ) {
        return getDelegate().exportAllConfigs(envs);
    }


    /**
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export : 导出应用配置(new added)
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export
     *
     * @param appId  (required)
     * @param env  (required)
     * @param clusterName  (required)
     * @return 成功导出应用配置 (status code 200)
     */
    @Operation(
        operationId = "exportAppConfig",
        summary = "导出应用配置(new added)",
        description = "GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功导出应用配置", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export",
        produces = { "application/octet-stream" }
    )
    default ResponseEntity<org.springframework.core.io.Resource> exportAppConfig(
        @Parameter(name = "appId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("appId") String appId,
        @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH) @PathVariable("env") String env,
        @Parameter(name = "clusterName", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clusterName") String clusterName
    ) {
        return getDelegate().exportAppConfig(appId, env, clusterName);
    }


    /**
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/export : 导出命名空间配置项(new added)
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/export
     *
     * @param appId  (required)
     * @param env  (required)
     * @param clusterName  (required)
     * @param namespaceName  (required)
     * @return 成功导出命名空间配置项 (status code 200)
     */
    @Operation(
        operationId = "exportNamespaceItems",
        summary = "导出命名空间配置项(new added)",
        description = "GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/export",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功导出命名空间配置项", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/export",
        produces = { "application/octet-stream" }
    )
    default ResponseEntity<org.springframework.core.io.Resource> exportNamespaceItems(
        @Parameter(name = "appId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("appId") String appId,
        @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH) @PathVariable("env") String env,
        @Parameter(name = "clusterName", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clusterName") String clusterName,
        @Parameter(name = "namespaceName", description = "", required = true, in = ParameterIn.PATH) @PathVariable("namespaceName") String namespaceName
    ) {
        return getDelegate().exportNamespaceItems(appId, env, clusterName, namespaceName);
    }


    /**
     * GET /openapi/v1/server/envs/{env}/config-db/config/find-all-config : 查询指定环境全部Config DB配置(new added)
     * GET /openapi/v1/server/envs/{env}/config-db/config/find-all-config
     *
     * @param env  (required)
     * @return 成功获取配置列表 (status code 200)
     */
    @Operation(
        operationId = "findAllConfigDBConfig",
        summary = "查询指定环境全部Config DB配置(new added)",
        description = "GET /openapi/v1/server/envs/{env}/config-db/config/find-all-config",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取配置列表", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/server/envs/{env}/config-db/config/find-all-config",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Object>> findAllConfigDBConfig(
        @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH) @PathVariable("env") String env
    ) {
        return getDelegate().findAllConfigDBConfig(env);
    }


    /**
     * GET /openapi/v1/server/portal-db/config/find-all-config : 查询全部Portal DB配置(new added)
     * GET /openapi/v1/server/portal-db/config/find-all-config
     *
     * @return 成功获取配置列表 (status code 200)
     */
    @Operation(
        operationId = "findAllPortalDBConfig",
        summary = "查询全部Portal DB配置(new added)",
        description = "GET /openapi/v1/server/portal-db/config/find-all-config",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取配置列表", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/server/portal-db/config/find-all-config",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Object>> findAllPortalDBConfig(

    ) {
        return getDelegate().findAllPortalDBConfig();
    }


    /**
     * GET /openapi/v1/apollo/audit/logs/dataInfluences/field : 查询审计数据影响(new added)
     * GET /openapi/v1/apollo/audit/logs/dataInfluences/field
     *
     * @param entityName  (required)
     * @param entityId  (required)
     * @param fieldName  (required)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @return 成功获取审计数据影响 (status code 200)
     */
    @Operation(
        operationId = "findAuditDataInfluencesByField",
        summary = "查询审计数据影响(new added)",
        description = "GET /openapi/v1/apollo/audit/logs/dataInfluences/field",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取审计数据影响", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/apollo/audit/logs/dataInfluences/field",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Object>> findAuditDataInfluencesByField(
        @NotNull @Parameter(name = "entityName", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "entityName", required = true) String entityName,
        @NotNull @Parameter(name = "entityId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "entityId", required = true) String entityId,
        @NotNull @Parameter(name = "fieldName", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "fieldName", required = true) String fieldName,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size
    ) {
        return getDelegate().findAuditDataInfluencesByField(entityName, entityId, fieldName, page, size);
    }


    /**
     * GET /openapi/v1/apollo/audit/logs : 查询审计日志(new added)
     * GET /openapi/v1/apollo/audit/logs
     *
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @return 成功获取审计日志 (status code 200)
     */
    @Operation(
        operationId = "findAuditLogs",
        summary = "查询审计日志(new added)",
        description = "GET /openapi/v1/apollo/audit/logs",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取审计日志", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/apollo/audit/logs",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Object>> findAuditLogs(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size
    ) {
        return getDelegate().findAuditLogs(page, size);
    }


    /**
     * GET /openapi/v1/apollo/audit/logs/opName : 按操作名查询审计日志(new added)
     * GET /openapi/v1/apollo/audit/logs/opName
     *
     * @param opName  (required)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @param startDate  (optional)
     * @param endDate  (optional)
     * @return 成功获取审计日志 (status code 200)
     */
    @Operation(
        operationId = "findAuditLogsByOpName",
        summary = "按操作名查询审计日志(new added)",
        description = "GET /openapi/v1/apollo/audit/logs/opName",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取审计日志", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/apollo/audit/logs/opName",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Object>> findAuditLogsByOpName(
        @NotNull @Parameter(name = "opName", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "opName", required = true) String opName,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size,
        @Parameter(name = "startDate", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "startDate", required = false) String startDate,
        @Parameter(name = "endDate", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "endDate", required = false) String endDate
    ) {
        return getDelegate().findAuditLogsByOpName(opName, page, size, startDate, endDate);
    }


    /**
     * GET /openapi/v1/apollo/audit/trace : 查询审计链路详情(new added)
     * GET /openapi/v1/apollo/audit/trace
     *
     * @param traceId  (required)
     * @return 成功获取审计链路详情 (status code 200)
     */
    @Operation(
        operationId = "findAuditTraceDetails",
        summary = "查询审计链路详情(new added)",
        description = "GET /openapi/v1/apollo/audit/trace",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取审计链路详情", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/apollo/audit/trace",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Object>> findAuditTraceDetails(
        @NotNull @Parameter(name = "traceId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "traceId", required = true) String traceId
    ) {
        return getDelegate().findAuditTraceDetails(traceId);
    }


    /**
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/commits : 查询命名空间提交记录(new added)
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/commits
     *
     * @param appId  (required)
     * @param env  (required)
     * @param clusterName  (required)
     * @param namespaceName  (required)
     * @param key  (optional)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @return 成功获取提交记录 (status code 200)
     */
    @Operation(
        operationId = "findCommits",
        summary = "查询命名空间提交记录(new added)",
        description = "GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/commits",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取提交记录", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/commits",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Object>> findCommits(
        @Parameter(name = "appId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("appId") String appId,
        @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH) @PathVariable("env") String env,
        @Parameter(name = "clusterName", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clusterName") String clusterName,
        @Parameter(name = "namespaceName", description = "", required = true, in = ParameterIn.PATH) @PathVariable("namespaceName") String namespaceName,
        @Parameter(name = "key", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "key", required = false) String key,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size
    ) {
        return getDelegate().findCommits(appId, env, clusterName, namespaceName, key, page, size);
    }


    /**
     * GET /openapi/v1/favorites : 查询收藏(new added)
     * GET /openapi/v1/favorites
     *
     * @param userId  (optional)
     * @param appId  (optional)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @return 成功获取收藏 (status code 200)
     */
    @Operation(
        operationId = "findFavorites",
        summary = "查询收藏(new added)",
        description = "GET /openapi/v1/favorites",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取收藏", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/favorites",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Object>> findFavorites(
        @Parameter(name = "userId", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = false) String userId,
        @Parameter(name = "appId", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "appId", required = false) String appId,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size
    ) {
        return getDelegate().findFavorites(userId, appId, page, size);
    }


    /**
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/releases/histories : 查询命名空间发布历史(new added)
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/releases/histories
     *
     * @param appId  (required)
     * @param env  (required)
     * @param clusterName  (required)
     * @param namespaceName  (required)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @return 成功获取发布历史 (status code 200)
     */
    @Operation(
        operationId = "findReleaseHistoriesByNamespace",
        summary = "查询命名空间发布历史(new added)",
        description = "GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/releases/histories",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取发布历史", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/releases/histories",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Object>> findReleaseHistoriesByNamespace(
        @Parameter(name = "appId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("appId") String appId,
        @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH) @PathVariable("env") String env,
        @Parameter(name = "clusterName", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clusterName") String clusterName,
        @Parameter(name = "namespaceName", description = "", required = true, in = ParameterIn.PATH) @PathVariable("namespaceName") String namespaceName,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size
    ) {
        return getDelegate().findReleaseHistoriesByNamespace(appId, env, clusterName, namespaceName, page, size);
    }


    /**
     * GET /openapi/v1/apollo/audit/properties : 获取审计配置(new added)
     * GET /openapi/v1/apollo/audit/properties
     *
     * @return 成功获取审计配置 (status code 200)
     */
    @Operation(
        operationId = "getAuditProperties",
        summary = "获取审计配置(new added)",
        description = "GET /openapi/v1/apollo/audit/properties",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取审计配置", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/apollo/audit/properties",
        produces = { "application/json" }
    )
    default ResponseEntity<Object> getAuditProperties(

    ) {
        return getDelegate().getAuditProperties();
    }


    /**
     * GET /openapi/v1/consumers : 查询开放平台消费者列表(new added)
     * GET /openapi/v1/consumers
     *
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @return 成功获取消费者列表 (status code 200)
     */
    @Operation(
        operationId = "getConsumerList",
        summary = "查询开放平台消费者列表(new added)",
        description = "GET /openapi/v1/consumers",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取消费者列表", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/consumers",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Object>> getConsumerList(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size
    ) {
        return getDelegate().getConsumerList(page, size);
    }


    /**
     * GET /openapi/v1/consumer-tokens/by-appId : 按应用ID查询消费者Token(new added)
     * GET /openapi/v1/consumer-tokens/by-appId
     *
     * @param appId  (required)
     * @return 成功获取消费者Token (status code 200)
     */
    @Operation(
        operationId = "getConsumerTokenByAppId",
        summary = "按应用ID查询消费者Token(new added)",
        description = "GET /openapi/v1/consumer-tokens/by-appId",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取消费者Token", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/consumer-tokens/by-appId",
        produces = { "application/json" }
    )
    default ResponseEntity<Object> getConsumerTokenByAppId(
        @NotNull @Parameter(name = "appId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "appId", required = true) String appId
    ) {
        return getDelegate().getConsumerTokenByAppId(appId);
    }


    /**
     * GET /openapi/v1/page-settings : 获取Portal页面配置(new added)
     * GET /openapi/v1/page-settings
     *
     * @return 成功获取页面配置 (status code 200)
     */
    @Operation(
        operationId = "getPageSettings",
        summary = "获取Portal页面配置(new added)",
        description = "GET /openapi/v1/page-settings",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取页面配置", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/page-settings",
        produces = { "application/json" }
    )
    default ResponseEntity<Object> getPageSettings(

    ) {
        return getDelegate().getPageSettings();
    }


    /**
     * GET /openapi/v1/system-info : 获取系统信息(new added)
     * GET /openapi/v1/system-info
     *
     * @return 成功获取系统信息 (status code 200)
     */
    @Operation(
        operationId = "getSystemInfo",
        summary = "获取系统信息(new added)",
        description = "GET /openapi/v1/system-info",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取系统信息", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/system-info",
        produces = { "application/json" }
    )
    default ResponseEntity<Object> getSystemInfo(

    ) {
        return getDelegate().getSystemInfo();
    }


    /**
     * POST /openapi/v1/configs/import : 导入所有配置(new added)
     * POST /openapi/v1/configs/import
     *
     * @param envs  (required)
     * @param conflictAction  (optional, default to ignore)
     * @param file  (optional)
     * @return 导入成功 (status code 200)
     */
    @Operation(
        operationId = "importAllConfigs",
        summary = "导入所有配置(new added)",
        description = "POST /openapi/v1/configs/import",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "导入成功")
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/openapi/v1/configs/import",
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<Void> importAllConfigs(
        @NotNull @Parameter(name = "envs", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "envs", required = true) String envs,
        @Parameter(name = "conflictAction", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "conflictAction", required = false, defaultValue = "ignore") String conflictAction,
        @Parameter(name = "file", description = "") @RequestPart(value = "file", required = false) MultipartFile file
    ) {
        return getDelegate().importAllConfigs(envs, conflictAction, file);
    }


    /**
     * POST /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/import : 导入应用配置(new added)
     * POST /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/import
     *
     * @param appId  (required)
     * @param env  (required)
     * @param clusterName  (required)
     * @param conflictAction  (optional, default to ignore)
     * @param file  (optional)
     * @return 导入成功 (status code 200)
     */
    @Operation(
        operationId = "importAppConfig",
        summary = "导入应用配置(new added)",
        description = "POST /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/import",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "导入成功")
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/import",
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<Void> importAppConfig(
        @Parameter(name = "appId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("appId") String appId,
        @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH) @PathVariable("env") String env,
        @Parameter(name = "clusterName", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clusterName") String clusterName,
        @Parameter(name = "conflictAction", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "conflictAction", required = false, defaultValue = "ignore") String conflictAction,
        @Parameter(name = "file", description = "") @RequestPart(value = "file", required = false) MultipartFile file
    ) {
        return getDelegate().importAppConfig(appId, env, clusterName, conflictAction, file);
    }


    /**
     * POST /openapi/v1/import : 导入配置兼容入口(new added)
     * POST /openapi/v1/import
     *
     * @param envs  (required)
     * @param conflictAction  (optional, default to ignore)
     * @param file  (optional)
     * @return 导入成功 (status code 200)
     */
    @Operation(
        operationId = "importConfig",
        summary = "导入配置兼容入口(new added)",
        description = "POST /openapi/v1/import",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "导入成功")
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/openapi/v1/import",
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<Void> importConfig(
        @NotNull @Parameter(name = "envs", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "envs", required = true) String envs,
        @Parameter(name = "conflictAction", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "conflictAction", required = false, defaultValue = "ignore") String conflictAction,
        @Parameter(name = "file", description = "") @RequestPart(value = "file", required = false) MultipartFile file
    ) {
        return getDelegate().importConfig(envs, conflictAction, file);
    }


    /**
     * POST /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/import : 导入命名空间配置项(new added)
     * POST /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/import
     *
     * @param appId  (required)
     * @param env  (required)
     * @param clusterName  (required)
     * @param namespaceName  (required)
     * @param file  (optional)
     * @return 导入成功 (status code 200)
     */
    @Operation(
        operationId = "importNamespaceItems",
        summary = "导入命名空间配置项(new added)",
        description = "POST /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/import",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "导入成功")
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/import",
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<Void> importNamespaceItems(
        @Parameter(name = "appId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("appId") String appId,
        @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH) @PathVariable("env") String env,
        @Parameter(name = "clusterName", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clusterName") String clusterName,
        @Parameter(name = "namespaceName", description = "", required = true, in = ParameterIn.PATH) @PathVariable("namespaceName") String namespaceName,
        @Parameter(name = "file", description = "") @RequestPart(value = "file", required = false) MultipartFile file
    ) {
        return getDelegate().importNamespaceItems(appId, env, clusterName, namespaceName, file);
    }


    /**
     * GET /openapi/v1/apps/search/by-appid-or-name : 按应用ID或名称搜索应用(new added)
     * GET /openapi/v1/apps/search/by-appid-or-name
     *
     * @param query  (optional)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 20)
     * @return 成功搜索应用 (status code 200)
     */
    @Operation(
        operationId = "searchAppsByAppIdOrName",
        summary = "按应用ID或名称搜索应用(new added)",
        description = "GET /openapi/v1/apps/search/by-appid-or-name",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功搜索应用", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/apps/search/by-appid-or-name",
        produces = { "application/json" }
    )
    default ResponseEntity<Object> searchAppsByAppIdOrName(
        @Parameter(name = "query", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "query", required = false) String query,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size
    ) {
        return getDelegate().searchAppsByAppIdOrName(query, page, size);
    }


    /**
     * GET /openapi/v1/apollo/audit/logs/by-name-or-type-or-operator : 搜索审计日志(new added)
     * GET /openapi/v1/apollo/audit/logs/by-name-or-type-or-operator
     *
     * @param query  (required)
     * @param page  (optional, default to 0)
     * @param size  (optional, default to 10)
     * @return 成功搜索审计日志 (status code 200)
     */
    @Operation(
        operationId = "searchAuditLogs",
        summary = "搜索审计日志(new added)",
        description = "GET /openapi/v1/apollo/audit/logs/by-name-or-type-or-operator",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功搜索审计日志", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Object.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/apollo/audit/logs/by-name-or-type-or-operator",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Object>> searchAuditLogs(
        @NotNull @Parameter(name = "query", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "query", required = true) String query,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size
    ) {
        return getDelegate().searchAuditLogs(query, page, size);
    }


    /**
     * GET /openapi/v1/global-search/item-info/by-key-or-value : 按Key或Value全局搜索配置(new added)
     * GET /openapi/v1/global-search/item-info/by-key-or-value
     *
     * @param key  (optional, default to )
     * @param value  (optional, default to )
     * @return 成功搜索配置 (status code 200)
     */
    @Operation(
        operationId = "searchItemInfoByKeyOrValue",
        summary = "按Key或Value全局搜索配置(new added)",
        description = "GET /openapi/v1/global-search/item-info/by-key-or-value",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功搜索配置", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/global-search/item-info/by-key-or-value",
        produces = { "application/json" }
    )
    default ResponseEntity<Object> searchItemInfoByKeyOrValue(
        @Parameter(name = "key", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "key", required = false, defaultValue = "") String key,
        @Parameter(name = "value", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "value", required = false, defaultValue = "") String value
    ) {
        return getDelegate().searchItemInfoByKeyOrValue(key, value);
    }


    /**
     * PUT /openapi/v1/favorites/{favoriteId} : 收藏置顶(new added)
     * PUT /openapi/v1/favorites/{favoriteId}
     *
     * @param favoriteId  (required)
     * @return 成功置顶收藏 (status code 200)
     */
    @Operation(
        operationId = "topFavorite",
        summary = "收藏置顶(new added)",
        description = "PUT /openapi/v1/favorites/{favoriteId}",
        tags = { "Portal Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功置顶收藏")
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/openapi/v1/favorites/{favoriteId}"
    )
    default ResponseEntity<Void> topFavorite(
        @Parameter(name = "favoriteId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("favoriteId") Long favoriteId
    ) {
        return getDelegate().topFavorite(favoriteId);
    }

}
