/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.apollo.openapi.server.api;

import com.apollo.openapi.server.model.ExceptionResponse;
import com.apollo.openapi.server.model.OpenUserDTO;
import com.apollo.openapi.server.model.OpenUserInfoDTO;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "User Management", description = "用户管理相关接口，支持Portal用户登录态和具备用户管理权限的Consumer Token调用")
public interface UserManagementApi {

    default UserManagementApiDelegate getDelegate() {
        return new UserManagementApiDelegate() {};
    }

    /**
     * PUT /openapi/v1/users/enabled : 修改用户启用状态(new added)
     * PUT /openapi/v1/users/enabled，Portal用户登录态使用当前登录用户作为operator；Consumer Token访问时需要具备ManageUsers权限并传入有效operator
     *
     * @param openUserDTO  (required)
     * @param operator 操作人用户名，Consumer Token访问时必填且必须是已存在用户；Portal用户登录态会忽略该参数 (optional)
     * @return 用户状态修改成功 (status code 200)
     *         or 请求参数错误 (status code 400)
     *         or 权限不足 (status code 403)
     */
    @Operation(
        operationId = "changeUserEnabled",
        summary = "修改用户启用状态(new added)",
        description = "PUT /openapi/v1/users/enabled，Portal用户登录态使用当前登录用户作为operator；Consumer Token访问时需要具备ManageUsers权限并传入有效operator",
        tags = { "User Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "用户状态修改成功"),
            @ApiResponse(responseCode = "400", description = "请求参数错误", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExceptionResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "权限不足", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExceptionResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/openapi/v1/users/enabled",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> changeUserEnabled(
        @Parameter(name = "OpenUserDTO", description = "", required = true) @Valid @RequestBody OpenUserDTO openUserDTO,
        @Parameter(name = "operator", description = "操作人用户名，Consumer Token访问时必填且必须是已存在用户；Portal用户登录态会忽略该参数", in = ParameterIn.QUERY) @Valid @RequestParam(value = "operator", required = false) String operator
    ) {
        return getDelegate().changeUserEnabled(openUserDTO, operator);
    }


    /**
     * POST /openapi/v1/users : 创建或更新用户(new added)
     * POST /openapi/v1/users，Portal用户登录态使用当前登录用户作为operator；Consumer Token访问时需要具备ManageUsers权限并传入有效operator
     *
     * @param openUserDTO  (required)
     * @param isCreate true 表示创建用户，false 表示更新用户 (optional, default to false)
     * @param operator 操作人用户名，Consumer Token访问时必填且必须是已存在用户；Portal用户登录态会忽略该参数 (optional)
     * @return 用户创建或更新成功 (status code 200)
     *         or 请求参数错误 (status code 400)
     *         or 权限不足 (status code 403)
     */
    @Operation(
        operationId = "createOrUpdateUser",
        summary = "创建或更新用户(new added)",
        description = "POST /openapi/v1/users，Portal用户登录态使用当前登录用户作为operator；Consumer Token访问时需要具备ManageUsers权限并传入有效operator",
        tags = { "User Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "用户创建或更新成功"),
            @ApiResponse(responseCode = "400", description = "请求参数错误", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExceptionResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "权限不足", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExceptionResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/openapi/v1/users",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createOrUpdateUser(
        @Parameter(name = "OpenUserDTO", description = "", required = true) @Valid @RequestBody OpenUserDTO openUserDTO,
        @Parameter(name = "isCreate", description = "true 表示创建用户，false 表示更新用户", in = ParameterIn.QUERY) @Valid @RequestParam(value = "isCreate", required = false, defaultValue = "false") Boolean isCreate,
        @Parameter(name = "operator", description = "操作人用户名，Consumer Token访问时必填且必须是已存在用户；Portal用户登录态会忽略该参数", in = ParameterIn.QUERY) @Valid @RequestParam(value = "operator", required = false) String operator
    ) {
        return getDelegate().createOrUpdateUser(openUserDTO, isCreate, operator);
    }


    /**
     * GET /openapi/v1/user : 获取当前Portal用户(new added)
     * GET /openapi/v1/user
     *
     * @return 成功获取当前用户 (status code 200)
     *         or 未登录或未授权访问 (status code 401)
     *         or 仅支持Portal用户登录态访问 (status code 403)
     */
    @Operation(
        operationId = "getCurrentUser",
        summary = "获取当前Portal用户(new added)",
        description = "GET /openapi/v1/user",
        tags = { "User Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取当前用户", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OpenUserInfoDTO.class))
            }),
            @ApiResponse(responseCode = "401", description = "未登录或未授权访问", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExceptionResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "仅支持Portal用户登录态访问", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExceptionResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/user",
        produces = { "application/json" }
    )
    default ResponseEntity<OpenUserInfoDTO> getCurrentUser(

    ) {
        return getDelegate().getCurrentUser();
    }


    /**
     * GET /openapi/v1/users/{userId} : 获取指定用户(new added)
     * GET /openapi/v1/users/{userId}，支持Portal用户登录态或具备ManageUsers权限的Consumer Token访问
     *
     * @param userId 用户ID (required)
     * @return 成功获取用户 (status code 200)
     *         or 请求参数错误或用户不存在 (status code 400)
     *         or 未登录或未认证 (status code 401)
     *         or 权限不足 (status code 403)
     */
    @Operation(
        operationId = "getUserByUserId",
        summary = "获取指定用户(new added)",
        description = "GET /openapi/v1/users/{userId}，支持Portal用户登录态或具备ManageUsers权限的Consumer Token访问",
        tags = { "User Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取用户", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OpenUserInfoDTO.class))
            }),
            @ApiResponse(responseCode = "400", description = "请求参数错误或用户不存在", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExceptionResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "未登录或未认证", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExceptionResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "权限不足", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExceptionResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/users/{userId}",
        produces = { "application/json" }
    )
    default ResponseEntity<OpenUserInfoDTO> getUserByUserId(
        @Parameter(name = "userId", description = "用户ID", required = true, in = ParameterIn.PATH) @PathVariable("userId") String userId
    ) {
        return getDelegate().getUserByUserId(userId);
    }


    /**
     * GET /openapi/v1/users : 搜索用户(new added)
     * GET /openapi/v1/users，支持Portal用户登录态或具备ManageUsers权限的Consumer Token访问
     *
     * @param keyword 用户名、显示名或邮箱关键字 (required)
     * @param includeInactiveUsers 是否包含禁用用户 (optional, default to false)
     * @param offset 偏移量 (optional, default to 0)
     * @param limit 返回数量 (optional, default to 10)
     * @return 成功获取用户列表 (status code 200)
     *         or 未登录或未授权访问 (status code 401)
     *         or 权限不足 (status code 403)
     */
    @Operation(
        operationId = "searchUsers",
        summary = "搜索用户(new added)",
        description = "GET /openapi/v1/users，支持Portal用户登录态或具备ManageUsers权限的Consumer Token访问",
        tags = { "User Management" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取用户列表", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = OpenUserInfoDTO.class)))
            }),
            @ApiResponse(responseCode = "401", description = "未登录或未授权访问", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExceptionResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "权限不足", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ExceptionResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "ApiKeyAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/openapi/v1/users",
        produces = { "application/json" }
    )
    default ResponseEntity<List<OpenUserInfoDTO>> searchUsers(
        @NotNull @Parameter(name = "keyword", description = "用户名、显示名或邮箱关键字", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "keyword", required = true) String keyword,
        @Parameter(name = "includeInactiveUsers", description = "是否包含禁用用户", in = ParameterIn.QUERY) @Valid @RequestParam(value = "includeInactiveUsers", required = false, defaultValue = "false") Boolean includeInactiveUsers,
        @Min(0) @Parameter(name = "offset", description = "偏移量", in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = false, defaultValue = "0") Integer offset,
        @Min(1) @Parameter(name = "limit", description = "返回数量", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "10") Integer limit
    ) {
        return getDelegate().searchUsers(keyword, includeInactiveUsers, offset, limit);
    }

}
