# coding: utf-8

"""
    Apollo OpenAPI

    <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>   # noqa: E501

    Generated by: https://openapi-generator.tech
"""

from apollo_openapi.paths.openapi_v1_favorites.post import AddFavorite
from apollo_openapi.paths.openapi_v1_consumers_token_assign_role.post import AssignRoleToConsumer
from apollo_openapi.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_export.head import CheckExportAppConfig
from apollo_openapi.paths.openapi_v1_system_info_health.get import CheckSystemHealth
from apollo_openapi.paths.openapi_v1_consumers.post import CreateConsumer
from apollo_openapi.paths.openapi_v1_server_envs_env_config_db_config.post import CreateOrUpdateConfigDbConfig
from apollo_openapi.paths.openapi_v1_server_portal_db_config.post import CreateOrUpdatePortalDbConfig
from apollo_openapi.paths.openapi_v1_server_envs_env_config_db_config.delete import DeleteConfigDbConfig
from apollo_openapi.paths.openapi_v1_consumers_by_app_id.delete import DeleteConsumer
from apollo_openapi.paths.openapi_v1_favorites_favorite_id.delete import DeleteFavorite
from apollo_openapi.paths.openapi_v1_server_portal_db_config.delete import DeletePortalDbConfig
from apollo_openapi.paths.openapi_v1_configs_export.get import ExportAllConfigs
from apollo_openapi.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_export.get import ExportAppConfig
from apollo_openapi.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_namespace_name_items_export.get import ExportNamespaceItems
from apollo_openapi.paths.openapi_v1_server_envs_env_config_db_config_find_all_config.get import FindAllConfigDbConfig
from apollo_openapi.paths.openapi_v1_server_portal_db_config_find_all_config.get import FindAllPortalDbConfig
from apollo_openapi.paths.openapi_v1_apollo_audit_logs_data_influences_field.get import FindAuditDataInfluencesByField
from apollo_openapi.paths.openapi_v1_apollo_audit_logs.get import FindAuditLogs
from apollo_openapi.paths.openapi_v1_apollo_audit_logs_op_name.get import FindAuditLogsByOpName
from apollo_openapi.paths.openapi_v1_apollo_audit_trace.get import FindAuditTraceDetails
from apollo_openapi.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_namespace_name_commits.get import FindCommits
from apollo_openapi.paths.openapi_v1_favorites.get import FindFavorites
from apollo_openapi.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_namespace_name_releases_histories.get import FindReleaseHistoriesByNamespace
from apollo_openapi.paths.openapi_v1_apollo_audit_properties.get import GetAuditProperties
from apollo_openapi.paths.openapi_v1_consumers.get import GetConsumerList
from apollo_openapi.paths.openapi_v1_consumer_tokens_by_app_id.get import GetConsumerTokenByAppId
from apollo_openapi.paths.openapi_v1_page_settings.get import GetPageSettings
from apollo_openapi.paths.openapi_v1_system_info.get import GetSystemInfo
from apollo_openapi.paths.openapi_v1_configs_import.post import ImportAllConfigs
from apollo_openapi.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_import.post import ImportAppConfig
from apollo_openapi.paths.openapi_v1_import.post import ImportConfig
from apollo_openapi.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_namespace_name_items_import.post import ImportNamespaceItems
from apollo_openapi.paths.openapi_v1_apps_search_by_appid_or_name.get import SearchAppsByAppIdOrName
from apollo_openapi.paths.openapi_v1_apollo_audit_logs_by_name_or_type_or_operator.get import SearchAuditLogs
from apollo_openapi.paths.openapi_v1_global_search_item_info_by_key_or_value.get import SearchItemInfoByKeyOrValue
from apollo_openapi.paths.openapi_v1_favorites_favorite_id.put import TopFavorite


class PortalManagementApi(
    AddFavorite,
    AssignRoleToConsumer,
    CheckExportAppConfig,
    CheckSystemHealth,
    CreateConsumer,
    CreateOrUpdateConfigDbConfig,
    CreateOrUpdatePortalDbConfig,
    DeleteConfigDbConfig,
    DeleteConsumer,
    DeleteFavorite,
    DeletePortalDbConfig,
    ExportAllConfigs,
    ExportAppConfig,
    ExportNamespaceItems,
    FindAllConfigDbConfig,
    FindAllPortalDbConfig,
    FindAuditDataInfluencesByField,
    FindAuditLogs,
    FindAuditLogsByOpName,
    FindAuditTraceDetails,
    FindCommits,
    FindFavorites,
    FindReleaseHistoriesByNamespace,
    GetAuditProperties,
    GetConsumerList,
    GetConsumerTokenByAppId,
    GetPageSettings,
    GetSystemInfo,
    ImportAllConfigs,
    ImportAppConfig,
    ImportConfig,
    ImportNamespaceItems,
    SearchAppsByAppIdOrName,
    SearchAuditLogs,
    SearchItemInfoByKeyOrValue,
    TopFavorite,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
