/*
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OpenConsumerTokenDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OpenConsumerTokenDTO {
  public static final String SERIALIZED_NAME_CONSUMER_ID = "consumerId";
  @SerializedName(SERIALIZED_NAME_CONSUMER_ID)
  private Long consumerId;

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  private String token;

  public static final String SERIALIZED_NAME_RATE_LIMIT = "rateLimit";
  @SerializedName(SERIALIZED_NAME_RATE_LIMIT)
  private Integer rateLimit = 0;

  public static final String SERIALIZED_NAME_EXPIRES = "expires";
  @SerializedName(SERIALIZED_NAME_EXPIRES)
  private OffsetDateTime expires;

  public static final String SERIALIZED_NAME_DATA_CHANGE_CREATED_BY = "dataChangeCreatedBy";
  @SerializedName(SERIALIZED_NAME_DATA_CHANGE_CREATED_BY)
  private String dataChangeCreatedBy;

  public static final String SERIALIZED_NAME_DATA_CHANGE_CREATED_TIME = "dataChangeCreatedTime";
  @SerializedName(SERIALIZED_NAME_DATA_CHANGE_CREATED_TIME)
  private OffsetDateTime dataChangeCreatedTime;

  public static final String SERIALIZED_NAME_DATA_CHANGE_LAST_MODIFIED_BY = "dataChangeLastModifiedBy";
  @SerializedName(SERIALIZED_NAME_DATA_CHANGE_LAST_MODIFIED_BY)
  private String dataChangeLastModifiedBy;

  public static final String SERIALIZED_NAME_DATA_CHANGE_LAST_MODIFIED_TIME = "dataChangeLastModifiedTime";
  @SerializedName(SERIALIZED_NAME_DATA_CHANGE_LAST_MODIFIED_TIME)
  private OffsetDateTime dataChangeLastModifiedTime;

  public OpenConsumerTokenDTO() {
  }

  public OpenConsumerTokenDTO consumerId(Long consumerId) {

    this.consumerId = consumerId;
    return this;
  }

   /**
   * Consumer ID
   * @return consumerId
  **/
  @javax.annotation.Nullable
  public Long getConsumerId() {
    return consumerId;
  }


  public void setConsumerId(Long consumerId) {
    this.consumerId = consumerId;
  }


  public OpenConsumerTokenDTO token(String token) {

    this.token = token;
    return this;
  }

   /**
   * Consumer Token
   * @return token
  **/
  @javax.annotation.Nullable
  public String getToken() {
    return token;
  }


  public void setToken(String token) {
    this.token = token;
  }


  public OpenConsumerTokenDTO rateLimit(Integer rateLimit) {

    this.rateLimit = rateLimit;
    return this;
  }

   /**
   * 限流QPS，0表示不限流
   * minimum: 0
   * @return rateLimit
  **/
  @javax.annotation.Nullable
  public Integer getRateLimit() {
    return rateLimit;
  }


  public void setRateLimit(Integer rateLimit) {
    this.rateLimit = rateLimit;
  }


  public OpenConsumerTokenDTO expires(OffsetDateTime expires) {

    this.expires = expires;
    return this;
  }

   /**
   * 过期时间
   * @return expires
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getExpires() {
    return expires;
  }


  public void setExpires(OffsetDateTime expires) {
    this.expires = expires;
  }


  public OpenConsumerTokenDTO dataChangeCreatedBy(String dataChangeCreatedBy) {

    this.dataChangeCreatedBy = dataChangeCreatedBy;
    return this;
  }

   /**
   * 创建人
   * @return dataChangeCreatedBy
  **/
  @javax.annotation.Nullable
  public String getDataChangeCreatedBy() {
    return dataChangeCreatedBy;
  }


  public void setDataChangeCreatedBy(String dataChangeCreatedBy) {
    this.dataChangeCreatedBy = dataChangeCreatedBy;
  }


  public OpenConsumerTokenDTO dataChangeCreatedTime(OffsetDateTime dataChangeCreatedTime) {

    this.dataChangeCreatedTime = dataChangeCreatedTime;
    return this;
  }

   /**
   * 创建时间
   * @return dataChangeCreatedTime
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getDataChangeCreatedTime() {
    return dataChangeCreatedTime;
  }


  public void setDataChangeCreatedTime(OffsetDateTime dataChangeCreatedTime) {
    this.dataChangeCreatedTime = dataChangeCreatedTime;
  }


  public OpenConsumerTokenDTO dataChangeLastModifiedBy(String dataChangeLastModifiedBy) {

    this.dataChangeLastModifiedBy = dataChangeLastModifiedBy;
    return this;
  }

   /**
   * 最后修改人
   * @return dataChangeLastModifiedBy
  **/
  @javax.annotation.Nullable
  public String getDataChangeLastModifiedBy() {
    return dataChangeLastModifiedBy;
  }


  public void setDataChangeLastModifiedBy(String dataChangeLastModifiedBy) {
    this.dataChangeLastModifiedBy = dataChangeLastModifiedBy;
  }


  public OpenConsumerTokenDTO dataChangeLastModifiedTime(OffsetDateTime dataChangeLastModifiedTime) {

    this.dataChangeLastModifiedTime = dataChangeLastModifiedTime;
    return this;
  }

   /**
   * 最后修改时间
   * @return dataChangeLastModifiedTime
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getDataChangeLastModifiedTime() {
    return dataChangeLastModifiedTime;
  }


  public void setDataChangeLastModifiedTime(OffsetDateTime dataChangeLastModifiedTime) {
    this.dataChangeLastModifiedTime = dataChangeLastModifiedTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenConsumerTokenDTO openConsumerTokenDTO = (OpenConsumerTokenDTO) o;
    return Objects.equals(this.consumerId, openConsumerTokenDTO.consumerId) &&
        Objects.equals(this.token, openConsumerTokenDTO.token) &&
        Objects.equals(this.rateLimit, openConsumerTokenDTO.rateLimit) &&
        Objects.equals(this.expires, openConsumerTokenDTO.expires) &&
        Objects.equals(this.dataChangeCreatedBy, openConsumerTokenDTO.dataChangeCreatedBy) &&
        Objects.equals(this.dataChangeCreatedTime, openConsumerTokenDTO.dataChangeCreatedTime) &&
        Objects.equals(this.dataChangeLastModifiedBy, openConsumerTokenDTO.dataChangeLastModifiedBy) &&
        Objects.equals(this.dataChangeLastModifiedTime, openConsumerTokenDTO.dataChangeLastModifiedTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consumerId, token, rateLimit, expires, dataChangeCreatedBy, dataChangeCreatedTime, dataChangeLastModifiedBy, dataChangeLastModifiedTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenConsumerTokenDTO {\n");
    sb.append("    consumerId: ").append(toIndentedString(consumerId)).append("\n");
    sb.append("    token: ").append(token == null ? "null" : "***redacted***").append("\n");
    sb.append("    rateLimit: ").append(toIndentedString(rateLimit)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    dataChangeCreatedBy: ").append(toIndentedString(dataChangeCreatedBy)).append("\n");
    sb.append("    dataChangeCreatedTime: ").append(toIndentedString(dataChangeCreatedTime)).append("\n");
    sb.append("    dataChangeLastModifiedBy: ").append(toIndentedString(dataChangeLastModifiedBy)).append("\n");
    sb.append("    dataChangeLastModifiedTime: ").append(toIndentedString(dataChangeLastModifiedTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("consumerId");
    openapiFields.add("token");
    openapiFields.add("rateLimit");
    openapiFields.add("expires");
    openapiFields.add("dataChangeCreatedBy");
    openapiFields.add("dataChangeCreatedTime");
    openapiFields.add("dataChangeLastModifiedBy");
    openapiFields.add("dataChangeLastModifiedTime");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OpenConsumerTokenDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!OpenConsumerTokenDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OpenConsumerTokenDTO is not found in the empty JSON string", OpenConsumerTokenDTO.openapiRequiredFields.toString()));
        }
        return;
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!OpenConsumerTokenDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OpenConsumerTokenDTO` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("token") != null && !jsonObj.get("token").isJsonNull()) && !jsonObj.get("token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token").toString()));
      }
      if ((jsonObj.get("dataChangeCreatedBy") != null && !jsonObj.get("dataChangeCreatedBy").isJsonNull()) && !jsonObj.get("dataChangeCreatedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dataChangeCreatedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataChangeCreatedBy").toString()));
      }
      if ((jsonObj.get("dataChangeLastModifiedBy") != null && !jsonObj.get("dataChangeLastModifiedBy").isJsonNull()) && !jsonObj.get("dataChangeLastModifiedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dataChangeLastModifiedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataChangeLastModifiedBy").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OpenConsumerTokenDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OpenConsumerTokenDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OpenConsumerTokenDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OpenConsumerTokenDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<OpenConsumerTokenDTO>() {
           @Override
           public void write(JsonWriter out, OpenConsumerTokenDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OpenConsumerTokenDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OpenConsumerTokenDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OpenConsumerTokenDTO
  * @throws IOException if the JSON string is invalid with respect to OpenConsumerTokenDTO
  */
  public static OpenConsumerTokenDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OpenConsumerTokenDTO.class);
  }

 /**
  * Convert an instance of OpenConsumerTokenDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
