/*
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OpenConsumerInfoDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OpenConsumerInfoDTO {
  public static final String SERIALIZED_NAME_APP_ID = "appId";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  private String appId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ORG_ID = "orgId";
  @SerializedName(SERIALIZED_NAME_ORG_ID)
  private String orgId;

  public static final String SERIALIZED_NAME_ORG_NAME = "orgName";
  @SerializedName(SERIALIZED_NAME_ORG_NAME)
  private String orgName;

  public static final String SERIALIZED_NAME_OWNER_NAME = "ownerName";
  @SerializedName(SERIALIZED_NAME_OWNER_NAME)
  private String ownerName;

  public static final String SERIALIZED_NAME_OWNER_EMAIL = "ownerEmail";
  @SerializedName(SERIALIZED_NAME_OWNER_EMAIL)
  private String ownerEmail;

  public static final String SERIALIZED_NAME_CONSUMER_ID = "consumerId";
  @SerializedName(SERIALIZED_NAME_CONSUMER_ID)
  private Long consumerId;

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  private String token;

  public static final String SERIALIZED_NAME_ALLOW_CREATE_APPLICATION = "allowCreateApplication";
  @SerializedName(SERIALIZED_NAME_ALLOW_CREATE_APPLICATION)
  private Boolean allowCreateApplication = false;

  public static final String SERIALIZED_NAME_ALLOW_MANAGE_USERS = "allowManageUsers";
  @SerializedName(SERIALIZED_NAME_ALLOW_MANAGE_USERS)
  private Boolean allowManageUsers = false;

  public static final String SERIALIZED_NAME_RATE_LIMIT = "rateLimit";
  @SerializedName(SERIALIZED_NAME_RATE_LIMIT)
  private Integer rateLimit = 0;

  public static final String SERIALIZED_NAME_RATE_LIMIT_ENABLED = "rateLimitEnabled";
  @SerializedName(SERIALIZED_NAME_RATE_LIMIT_ENABLED)
  private Boolean rateLimitEnabled = false;

  public OpenConsumerInfoDTO() {
  }

  public OpenConsumerInfoDTO appId(String appId) {

    this.appId = appId;
    return this;
  }

   /**
   * 第三方应用ID
   * @return appId
  **/
  @javax.annotation.Nullable
  public String getAppId() {
    return appId;
  }


  public void setAppId(String appId) {
    this.appId = appId;
  }


  public OpenConsumerInfoDTO name(String name) {

    this.name = name;
    return this;
  }

   /**
   * 第三方应用名称
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public OpenConsumerInfoDTO orgId(String orgId) {

    this.orgId = orgId;
    return this;
  }

   /**
   * 部门ID
   * @return orgId
  **/
  @javax.annotation.Nullable
  public String getOrgId() {
    return orgId;
  }


  public void setOrgId(String orgId) {
    this.orgId = orgId;
  }


  public OpenConsumerInfoDTO orgName(String orgName) {

    this.orgName = orgName;
    return this;
  }

   /**
   * 部门名称
   * @return orgName
  **/
  @javax.annotation.Nullable
  public String getOrgName() {
    return orgName;
  }


  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }


  public OpenConsumerInfoDTO ownerName(String ownerName) {

    this.ownerName = ownerName;
    return this;
  }

   /**
   * 负责人用户名
   * @return ownerName
  **/
  @javax.annotation.Nullable
  public String getOwnerName() {
    return ownerName;
  }


  public void setOwnerName(String ownerName) {
    this.ownerName = ownerName;
  }


  public OpenConsumerInfoDTO ownerEmail(String ownerEmail) {

    this.ownerEmail = ownerEmail;
    return this;
  }

   /**
   * 负责人邮箱
   * @return ownerEmail
  **/
  @javax.annotation.Nullable
  public String getOwnerEmail() {
    return ownerEmail;
  }


  public void setOwnerEmail(String ownerEmail) {
    this.ownerEmail = ownerEmail;
  }


  public OpenConsumerInfoDTO consumerId(Long consumerId) {

    this.consumerId = consumerId;
    return this;
  }

   /**
   * Consumer ID
   * @return consumerId
  **/
  @javax.annotation.Nullable
  public Long getConsumerId() {
    return consumerId;
  }


  public void setConsumerId(Long consumerId) {
    this.consumerId = consumerId;
  }


  public OpenConsumerInfoDTO token(String token) {

    this.token = token;
    return this;
  }

   /**
   * Consumer Token，仅在创建或按应用查询详情时返回
   * @return token
  **/
  @javax.annotation.Nullable
  public String getToken() {
    return token;
  }


  public void setToken(String token) {
    this.token = token;
  }


  public OpenConsumerInfoDTO allowCreateApplication(Boolean allowCreateApplication) {

    this.allowCreateApplication = allowCreateApplication;
    return this;
  }

   /**
   * 是否允许该Consumer Token创建应用
   * @return allowCreateApplication
  **/
  @javax.annotation.Nullable
  public Boolean getAllowCreateApplication() {
    return allowCreateApplication;
  }


  public void setAllowCreateApplication(Boolean allowCreateApplication) {
    this.allowCreateApplication = allowCreateApplication;
  }


  public OpenConsumerInfoDTO allowManageUsers(Boolean allowManageUsers) {

    this.allowManageUsers = allowManageUsers;
    return this;
  }

   /**
   * 是否允许该Consumer Token管理用户
   * @return allowManageUsers
  **/
  @javax.annotation.Nullable
  public Boolean getAllowManageUsers() {
    return allowManageUsers;
  }


  public void setAllowManageUsers(Boolean allowManageUsers) {
    this.allowManageUsers = allowManageUsers;
  }


  public OpenConsumerInfoDTO rateLimit(Integer rateLimit) {

    this.rateLimit = rateLimit;
    return this;
  }

   /**
   * 限流QPS，0表示不限流
   * minimum: 0
   * @return rateLimit
  **/
  @javax.annotation.Nullable
  public Integer getRateLimit() {
    return rateLimit;
  }


  public void setRateLimit(Integer rateLimit) {
    this.rateLimit = rateLimit;
  }


  public OpenConsumerInfoDTO rateLimitEnabled(Boolean rateLimitEnabled) {

    this.rateLimitEnabled = rateLimitEnabled;
    return this;
  }

   /**
   * 是否开启限流
   * @return rateLimitEnabled
  **/
  @javax.annotation.Nullable
  public Boolean getRateLimitEnabled() {
    return rateLimitEnabled;
  }


  public void setRateLimitEnabled(Boolean rateLimitEnabled) {
    this.rateLimitEnabled = rateLimitEnabled;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenConsumerInfoDTO openConsumerInfoDTO = (OpenConsumerInfoDTO) o;
    return Objects.equals(this.appId, openConsumerInfoDTO.appId) &&
        Objects.equals(this.name, openConsumerInfoDTO.name) &&
        Objects.equals(this.orgId, openConsumerInfoDTO.orgId) &&
        Objects.equals(this.orgName, openConsumerInfoDTO.orgName) &&
        Objects.equals(this.ownerName, openConsumerInfoDTO.ownerName) &&
        Objects.equals(this.ownerEmail, openConsumerInfoDTO.ownerEmail) &&
        Objects.equals(this.consumerId, openConsumerInfoDTO.consumerId) &&
        Objects.equals(this.token, openConsumerInfoDTO.token) &&
        Objects.equals(this.allowCreateApplication, openConsumerInfoDTO.allowCreateApplication) &&
        Objects.equals(this.allowManageUsers, openConsumerInfoDTO.allowManageUsers) &&
        Objects.equals(this.rateLimit, openConsumerInfoDTO.rateLimit) &&
        Objects.equals(this.rateLimitEnabled, openConsumerInfoDTO.rateLimitEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, name, orgId, orgName, ownerName, ownerEmail, consumerId, token, allowCreateApplication, allowManageUsers, rateLimit, rateLimitEnabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenConsumerInfoDTO {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    orgName: ").append(toIndentedString(orgName)).append("\n");
    sb.append("    ownerName: ").append(toIndentedString(ownerName)).append("\n");
    sb.append("    ownerEmail: ").append(toIndentedString(ownerEmail)).append("\n");
    sb.append("    consumerId: ").append(toIndentedString(consumerId)).append("\n");
    sb.append("    token: ").append(token == null ? "null" : "***redacted***").append("\n");
    sb.append("    allowCreateApplication: ").append(toIndentedString(allowCreateApplication)).append("\n");
    sb.append("    allowManageUsers: ").append(toIndentedString(allowManageUsers)).append("\n");
    sb.append("    rateLimit: ").append(toIndentedString(rateLimit)).append("\n");
    sb.append("    rateLimitEnabled: ").append(toIndentedString(rateLimitEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("appId");
    openapiFields.add("name");
    openapiFields.add("orgId");
    openapiFields.add("orgName");
    openapiFields.add("ownerName");
    openapiFields.add("ownerEmail");
    openapiFields.add("consumerId");
    openapiFields.add("token");
    openapiFields.add("allowCreateApplication");
    openapiFields.add("allowManageUsers");
    openapiFields.add("rateLimit");
    openapiFields.add("rateLimitEnabled");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OpenConsumerInfoDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!OpenConsumerInfoDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OpenConsumerInfoDTO is not found in the empty JSON string", OpenConsumerInfoDTO.openapiRequiredFields.toString()));
        }
        return;
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!OpenConsumerInfoDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OpenConsumerInfoDTO` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("appId") != null && !jsonObj.get("appId").isJsonNull()) && !jsonObj.get("appId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `appId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("appId").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("orgId") != null && !jsonObj.get("orgId").isJsonNull()) && !jsonObj.get("orgId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `orgId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("orgId").toString()));
      }
      if ((jsonObj.get("orgName") != null && !jsonObj.get("orgName").isJsonNull()) && !jsonObj.get("orgName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `orgName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("orgName").toString()));
      }
      if ((jsonObj.get("ownerName") != null && !jsonObj.get("ownerName").isJsonNull()) && !jsonObj.get("ownerName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ownerName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ownerName").toString()));
      }
      if ((jsonObj.get("ownerEmail") != null && !jsonObj.get("ownerEmail").isJsonNull()) && !jsonObj.get("ownerEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ownerEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ownerEmail").toString()));
      }
      if ((jsonObj.get("token") != null && !jsonObj.get("token").isJsonNull()) && !jsonObj.get("token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OpenConsumerInfoDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OpenConsumerInfoDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OpenConsumerInfoDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OpenConsumerInfoDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<OpenConsumerInfoDTO>() {
           @Override
           public void write(JsonWriter out, OpenConsumerInfoDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OpenConsumerInfoDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OpenConsumerInfoDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OpenConsumerInfoDTO
  * @throws IOException if the JSON string is invalid with respect to OpenConsumerInfoDTO
  */
  public static OpenConsumerInfoDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OpenConsumerInfoDTO.class);
  }

 /**
  * Convert an instance of OpenConsumerInfoDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
