# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import apollo_openapi
from apollo_openapi.paths.openapi_v1_consumers import post  # noqa: E501
from apollo_openapi import configuration, schemas, api_client

from .. import ApiTestMixin


class TestOpenapiV1Consumers(ApiTestMixin, unittest.TestCase):
    """
    OpenapiV1Consumers unit test stubs
        创建开放平台消费者(new added)  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
