/* tslint:disable */
/* eslint-disable */
/**
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OpenUserDTO
 */
export interface OpenUserDTO {
    /**
     * 用户名
     * @type {string}
     * @memberof OpenUserDTO
     */
    username?: string;
    /**
     * 用户显示名
     * @type {string}
     * @memberof OpenUserDTO
     */
    userDisplayName?: string;
    /**
     * 用户密码
     * @type {string}
     * @memberof OpenUserDTO
     */
    password?: string;
    /**
     * 用户邮箱
     * @type {string}
     * @memberof OpenUserDTO
     */
    email?: string;
    /**
     * 是否启用，1 表示启用，0 表示禁用
     * @type {number}
     * @memberof OpenUserDTO
     */
    enabled?: number;
}

/**
 * Check if a given object implements the OpenUserDTO interface.
 */
export function instanceOfOpenUserDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OpenUserDTOFromJSON(json: any): OpenUserDTO {
    return OpenUserDTOFromJSONTyped(json, false);
}

export function OpenUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenUserDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'username': !exists(json, 'username') ? undefined : json['username'],
        'userDisplayName': !exists(json, 'userDisplayName') ? undefined : json['userDisplayName'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function OpenUserDTOToJSON(value?: OpenUserDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'username': value.username,
        'userDisplayName': value.userDisplayName,
        'password': value.password,
        'email': value.email,
        'enabled': value.enabled,
    };
}
