/* tslint:disable */
/* eslint-disable */
/**
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OpenConsumerSummaryDTO
 */
export interface OpenConsumerSummaryDTO {
    /**
     * 第三方应用ID
     * @type {string}
     * @memberof OpenConsumerSummaryDTO
     */
    appId?: string;
    /**
     * 第三方应用名称
     * @type {string}
     * @memberof OpenConsumerSummaryDTO
     */
    name?: string;
    /**
     * 部门ID
     * @type {string}
     * @memberof OpenConsumerSummaryDTO
     */
    orgId?: string;
    /**
     * 部门名称
     * @type {string}
     * @memberof OpenConsumerSummaryDTO
     */
    orgName?: string;
    /**
     * 负责人用户名
     * @type {string}
     * @memberof OpenConsumerSummaryDTO
     */
    ownerName?: string;
    /**
     * 负责人邮箱
     * @type {string}
     * @memberof OpenConsumerSummaryDTO
     */
    ownerEmail?: string;
    /**
     * Consumer ID
     * @type {number}
     * @memberof OpenConsumerSummaryDTO
     */
    consumerId?: number;
    /**
     * 是否允许该Consumer Token创建应用
     * @type {boolean}
     * @memberof OpenConsumerSummaryDTO
     */
    allowCreateApplication?: boolean;
    /**
     * 是否允许该Consumer Token管理用户
     * @type {boolean}
     * @memberof OpenConsumerSummaryDTO
     */
    allowManageUsers?: boolean;
    /**
     * 限流QPS，0表示不限流
     * @type {number}
     * @memberof OpenConsumerSummaryDTO
     */
    rateLimit?: number;
    /**
     * 是否开启限流
     * @type {boolean}
     * @memberof OpenConsumerSummaryDTO
     */
    rateLimitEnabled?: boolean;
}

/**
 * Check if a given object implements the OpenConsumerSummaryDTO interface.
 */
export function instanceOfOpenConsumerSummaryDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OpenConsumerSummaryDTOFromJSON(json: any): OpenConsumerSummaryDTO {
    return OpenConsumerSummaryDTOFromJSONTyped(json, false);
}

export function OpenConsumerSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenConsumerSummaryDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'appId': !exists(json, 'appId') ? undefined : json['appId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'orgId': !exists(json, 'orgId') ? undefined : json['orgId'],
        'orgName': !exists(json, 'orgName') ? undefined : json['orgName'],
        'ownerName': !exists(json, 'ownerName') ? undefined : json['ownerName'],
        'ownerEmail': !exists(json, 'ownerEmail') ? undefined : json['ownerEmail'],
        'consumerId': !exists(json, 'consumerId') ? undefined : json['consumerId'],
        'allowCreateApplication': !exists(json, 'allowCreateApplication') ? undefined : json['allowCreateApplication'],
        'allowManageUsers': !exists(json, 'allowManageUsers') ? undefined : json['allowManageUsers'],
        'rateLimit': !exists(json, 'rateLimit') ? undefined : json['rateLimit'],
        'rateLimitEnabled': !exists(json, 'rateLimitEnabled') ? undefined : json['rateLimitEnabled'],
    };
}

export function OpenConsumerSummaryDTOToJSON(value?: OpenConsumerSummaryDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'appId': value.appId,
        'name': value.name,
        'orgId': value.orgId,
        'orgName': value.orgName,
        'ownerName': value.ownerName,
        'ownerEmail': value.ownerEmail,
        'consumerId': value.consumerId,
        'allowCreateApplication': value.allowCreateApplication,
        'allowManageUsers': value.allowManageUsers,
        'rateLimit': value.rateLimit,
        'rateLimitEnabled': value.rateLimitEnabled,
    };
}
