/* tslint:disable */
/* eslint-disable */
/**
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OpenConsumerCreateRequestDTO
 */
export interface OpenConsumerCreateRequestDTO {
    /**
     * 第三方应用ID
     * @type {string}
     * @memberof OpenConsumerCreateRequestDTO
     */
    appId: string;
    /**
     * 是否允许该Consumer Token创建应用
     * @type {boolean}
     * @memberof OpenConsumerCreateRequestDTO
     */
    allowCreateApplication?: boolean;
    /**
     * 是否允许该Consumer Token管理用户
     * @type {boolean}
     * @memberof OpenConsumerCreateRequestDTO
     */
    allowManageUsers?: boolean;
    /**
     * 第三方应用名称
     * @type {string}
     * @memberof OpenConsumerCreateRequestDTO
     */
    name: string;
    /**
     * 部门ID
     * @type {string}
     * @memberof OpenConsumerCreateRequestDTO
     */
    orgId: string;
    /**
     * 部门名称
     * @type {string}
     * @memberof OpenConsumerCreateRequestDTO
     */
    orgName?: string;
    /**
     * 负责人用户名
     * @type {string}
     * @memberof OpenConsumerCreateRequestDTO
     */
    ownerName: string;
    /**
     * 是否开启限流
     * @type {boolean}
     * @memberof OpenConsumerCreateRequestDTO
     */
    rateLimitEnabled?: boolean;
    /**
     * 限流QPS，rateLimitEnabled 为 true 时必须大于 0；未开启限流时 0 表示不限流
     * @type {number}
     * @memberof OpenConsumerCreateRequestDTO
     */
    rateLimit?: number;
}

/**
 * Check if a given object implements the OpenConsumerCreateRequestDTO interface.
 */
export function instanceOfOpenConsumerCreateRequestDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "appId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "orgId" in value;
    isInstance = isInstance && "ownerName" in value;

    return isInstance;
}

export function OpenConsumerCreateRequestDTOFromJSON(json: any): OpenConsumerCreateRequestDTO {
    return OpenConsumerCreateRequestDTOFromJSONTyped(json, false);
}

export function OpenConsumerCreateRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenConsumerCreateRequestDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'appId': json['appId'],
        'allowCreateApplication': !exists(json, 'allowCreateApplication') ? undefined : json['allowCreateApplication'],
        'allowManageUsers': !exists(json, 'allowManageUsers') ? undefined : json['allowManageUsers'],
        'name': json['name'],
        'orgId': json['orgId'],
        'orgName': !exists(json, 'orgName') ? undefined : json['orgName'],
        'ownerName': json['ownerName'],
        'rateLimitEnabled': !exists(json, 'rateLimitEnabled') ? undefined : json['rateLimitEnabled'],
        'rateLimit': !exists(json, 'rateLimit') ? undefined : json['rateLimit'],
    };
}

export function OpenConsumerCreateRequestDTOToJSON(value?: OpenConsumerCreateRequestDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'appId': value.appId,
        'allowCreateApplication': value.allowCreateApplication,
        'allowManageUsers': value.allowManageUsers,
        'name': value.name,
        'orgId': value.orgId,
        'orgName': value.orgName,
        'ownerName': value.ownerName,
        'rateLimitEnabled': value.rateLimitEnabled,
        'rateLimit': value.rateLimit,
    };
}
