/* tslint:disable */
/* eslint-disable */
/**
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OpenConsumerTokenDTO
 */
export interface OpenConsumerTokenDTO {
    /**
     * Consumer Token ID
     * @type {number}
     * @memberof OpenConsumerTokenDTO
     */
    id?: number;
    /**
     * 是否已删除
     * @type {boolean}
     * @memberof OpenConsumerTokenDTO
     */
    deleted?: boolean;
    /**
     * 删除时间戳
     * @type {number}
     * @memberof OpenConsumerTokenDTO
     */
    deletedAt?: number;
    /**
     * Consumer ID
     * @type {number}
     * @memberof OpenConsumerTokenDTO
     */
    consumerId?: number;
    /**
     * Consumer Token
     * @type {string}
     * @memberof OpenConsumerTokenDTO
     */
    token?: string | null;
    /**
     * 限流QPS，0表示不限流
     * @type {number}
     * @memberof OpenConsumerTokenDTO
     */
    rateLimit?: number;
    /**
     * 过期时间
     * @type {Date}
     * @memberof OpenConsumerTokenDTO
     */
    expires?: Date;
    /**
     * 创建人
     * @type {string}
     * @memberof OpenConsumerTokenDTO
     */
    dataChangeCreatedBy?: string;
    /**
     * 创建时间
     * @type {Date}
     * @memberof OpenConsumerTokenDTO
     */
    dataChangeCreatedTime?: Date;
    /**
     * 最后修改人
     * @type {string}
     * @memberof OpenConsumerTokenDTO
     */
    dataChangeLastModifiedBy?: string;
    /**
     * 最后修改时间
     * @type {Date}
     * @memberof OpenConsumerTokenDTO
     */
    dataChangeLastModifiedTime?: Date;
}

/**
 * Check if a given object implements the OpenConsumerTokenDTO interface.
 */
export function instanceOfOpenConsumerTokenDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OpenConsumerTokenDTOFromJSON(json: any): OpenConsumerTokenDTO {
    return OpenConsumerTokenDTOFromJSONTyped(json, false);
}

export function OpenConsumerTokenDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenConsumerTokenDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': !exists(json, 'id') ? undefined : json['id'],
        'deleted': !exists(json, 'deleted') ? undefined : json['deleted'],
        'deletedAt': !exists(json, 'deletedAt') ? undefined : json['deletedAt'],
        'consumerId': !exists(json, 'consumerId') ? undefined : json['consumerId'],
        'token': !exists(json, 'token') ? undefined : json['token'],
        'rateLimit': !exists(json, 'rateLimit') ? undefined : json['rateLimit'],
        'expires': !exists(json, 'expires') ? undefined : (new Date(json['expires'])),
        'dataChangeCreatedBy': !exists(json, 'dataChangeCreatedBy') ? undefined : json['dataChangeCreatedBy'],
        'dataChangeCreatedTime': !exists(json, 'dataChangeCreatedTime') ? undefined : (new Date(json['dataChangeCreatedTime'])),
        'dataChangeLastModifiedBy': !exists(json, 'dataChangeLastModifiedBy') ? undefined : json['dataChangeLastModifiedBy'],
        'dataChangeLastModifiedTime': !exists(json, 'dataChangeLastModifiedTime') ? undefined : (new Date(json['dataChangeLastModifiedTime'])),
    };
}

export function OpenConsumerTokenDTOToJSON(value?: OpenConsumerTokenDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'deleted': value.deleted,
        'deletedAt': value.deletedAt,
        'consumerId': value.consumerId,
        'token': value.token,
        'rateLimit': value.rateLimit,
        'expires': value.expires === undefined ? undefined : (value.expires.toISOString()),
        'dataChangeCreatedBy': value.dataChangeCreatedBy,
        'dataChangeCreatedTime': value.dataChangeCreatedTime === undefined ? undefined : (value.dataChangeCreatedTime.toISOString()),
        'dataChangeLastModifiedBy': value.dataChangeLastModifiedBy,
        'dataChangeLastModifiedTime': value.dataChangeLastModifiedTime === undefined ? undefined : (value.dataChangeLastModifiedTime.toISOString()),
    };
}
