/*
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ExceptionResponse;
import org.openapitools.client.model.OpenUserDTO;
import org.openapitools.client.model.OpenUserInfoDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PortalUserManagementApi
 */
@Disabled
public class PortalUserManagementApiTest {

    private final PortalUserManagementApi api = new PortalUserManagementApi();

    /**
     * 修改Portal用户启用状态(new added)
     *
     * PUT /openapi/v1/users/enabled
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void changeUserEnabledTest() throws ApiException {
        OpenUserDTO openUserDTO = null;
        api.changeUserEnabled(openUserDTO);
        // TODO: test validations
    }

    /**
     * 创建或更新Portal用户(new added)
     *
     * POST /openapi/v1/users
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createOrUpdateUserTest() throws ApiException {
        OpenUserDTO openUserDTO = null;
        Boolean isCreate = null;
        api.createOrUpdateUser(openUserDTO, isCreate);
        // TODO: test validations
    }

    /**
     * 获取当前Portal用户(new added)
     *
     * GET /openapi/v1/user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCurrentUserTest() throws ApiException {
        OpenUserInfoDTO response = api.getCurrentUser();
        // TODO: test validations
    }

    /**
     * 搜索Portal用户(new added)
     *
     * GET /openapi/v1/users
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchUsersTest() throws ApiException {
        String keyword = null;
        Boolean includeInactiveUsers = null;
        Integer offset = null;
        Integer limit = null;
        List<OpenUserInfoDTO> response = api.searchUsers(keyword, includeInactiveUsers, offset, limit);
        // TODO: test validations
    }

}
