/*
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.io.File;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PortalManagementApi
 */
@Disabled
public class PortalManagementApiTest {

    private final PortalManagementApi api = new PortalManagementApi();

    /**
     * 添加收藏(new added)
     *
     * POST /openapi/v1/favorites
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addFavoriteTest() throws ApiException {
        Object body = null;
        Object response = api.addFavorite(body);
        // TODO: test validations
    }

    /**
     * 给消费者授权(new added)
     *
     * POST /openapi/v1/consumers/{token}/assign-role
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void assignRoleToConsumerTest() throws ApiException {
        String token = null;
        String type = null;
        Object body = null;
        String envs = null;
        List<Object> response = api.assignRoleToConsumer(token, type, body, envs);
        // TODO: test validations
    }

    /**
     * 检查应用配置导出权限(new added)
     *
     * HEAD /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkExportAppConfigTest() throws ApiException {
        String appId = null;
        String env = null;
        String clusterName = null;
        api.checkExportAppConfig(appId, env, clusterName);
        // TODO: test validations
    }

    /**
     * 检查系统实例健康状态(new added)
     *
     * GET /openapi/v1/system-info/health
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkSystemHealthTest() throws ApiException {
        String instanceId = null;
        Object response = api.checkSystemHealth(instanceId);
        // TODO: test validations
    }

    /**
     * 创建开放平台消费者(new added)
     *
     * POST /openapi/v1/consumers
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createConsumerTest() throws ApiException {
        Object body = null;
        String expires = null;
        Object response = api.createConsumer(body, expires);
        // TODO: test validations
    }

    /**
     * 创建或更新Config DB配置(new added)
     *
     * POST /openapi/v1/server/envs/{env}/config-db/config
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createOrUpdateConfigDBConfigTest() throws ApiException {
        String env = null;
        Object body = null;
        Object response = api.createOrUpdateConfigDBConfig(env, body);
        // TODO: test validations
    }

    /**
     * 创建或更新Portal DB配置(new added)
     *
     * POST /openapi/v1/server/portal-db/config
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createOrUpdatePortalDBConfigTest() throws ApiException {
        Object body = null;
        Object response = api.createOrUpdatePortalDBConfig(body);
        // TODO: test validations
    }

    /**
     * 删除Config DB配置(new added)
     *
     * DELETE /openapi/v1/server/envs/{env}/config-db/config
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteConfigDBConfigTest() throws ApiException {
        String env = null;
        String key = null;
        String cluster = null;
        api.deleteConfigDBConfig(env, key, cluster);
        // TODO: test validations
    }

    /**
     * 按应用ID删除消费者(new added)
     *
     * DELETE /openapi/v1/consumers/by-appId
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteConsumerTest() throws ApiException {
        String appId = null;
        api.deleteConsumer(appId);
        // TODO: test validations
    }

    /**
     * 删除收藏(new added)
     *
     * DELETE /openapi/v1/favorites/{favoriteId}
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteFavoriteTest() throws ApiException {
        Long favoriteId = null;
        api.deleteFavorite(favoriteId);
        // TODO: test validations
    }

    /**
     * 删除Portal DB配置(new added)
     *
     * DELETE /openapi/v1/server/portal-db/config
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deletePortalDBConfigTest() throws ApiException {
        String key = null;
        api.deletePortalDBConfig(key);
        // TODO: test validations
    }

    /**
     * 导出所有配置(new added)
     *
     * GET /openapi/v1/configs/export
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void exportAllConfigsTest() throws ApiException {
        String envs = null;
        File response = api.exportAllConfigs(envs);
        // TODO: test validations
    }

    /**
     * 导出应用配置(new added)
     *
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void exportAppConfigTest() throws ApiException {
        String appId = null;
        String env = null;
        String clusterName = null;
        File response = api.exportAppConfig(appId, env, clusterName);
        // TODO: test validations
    }

    /**
     * 导出命名空间配置项(new added)
     *
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/export
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void exportNamespaceItemsTest() throws ApiException {
        String appId = null;
        String env = null;
        String clusterName = null;
        String namespaceName = null;
        File response = api.exportNamespaceItems(appId, env, clusterName, namespaceName);
        // TODO: test validations
    }

    /**
     * 查询指定环境全部Config DB配置(new added)
     *
     * GET /openapi/v1/server/envs/{env}/config-db/config/find-all-config
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAllConfigDBConfigTest() throws ApiException {
        String env = null;
        List<Object> response = api.findAllConfigDBConfig(env);
        // TODO: test validations
    }

    /**
     * 查询全部Portal DB配置(new added)
     *
     * GET /openapi/v1/server/portal-db/config/find-all-config
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAllPortalDBConfigTest() throws ApiException {
        List<Object> response = api.findAllPortalDBConfig();
        // TODO: test validations
    }

    /**
     * 查询审计数据影响(new added)
     *
     * GET /openapi/v1/apollo/audit/logs/dataInfluences/field
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAuditDataInfluencesByFieldTest() throws ApiException {
        String entityName = null;
        String entityId = null;
        String fieldName = null;
        Integer page = null;
        Integer size = null;
        List<Object> response = api.findAuditDataInfluencesByField(entityName, entityId, fieldName, page, size);
        // TODO: test validations
    }

    /**
     * 查询审计日志(new added)
     *
     * GET /openapi/v1/apollo/audit/logs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAuditLogsTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        List<Object> response = api.findAuditLogs(page, size);
        // TODO: test validations
    }

    /**
     * 按操作名查询审计日志(new added)
     *
     * GET /openapi/v1/apollo/audit/logs/opName
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAuditLogsByOpNameTest() throws ApiException {
        String opName = null;
        Integer page = null;
        Integer size = null;
        String startDate = null;
        String endDate = null;
        List<Object> response = api.findAuditLogsByOpName(opName, page, size, startDate, endDate);
        // TODO: test validations
    }

    /**
     * 查询审计链路详情(new added)
     *
     * GET /openapi/v1/apollo/audit/trace
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAuditTraceDetailsTest() throws ApiException {
        String traceId = null;
        List<Object> response = api.findAuditTraceDetails(traceId);
        // TODO: test validations
    }

    /**
     * 查询命名空间提交记录(new added)
     *
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/commits
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findCommitsTest() throws ApiException {
        String appId = null;
        String env = null;
        String clusterName = null;
        String namespaceName = null;
        String key = null;
        Integer page = null;
        Integer size = null;
        List<Object> response = api.findCommits(appId, env, clusterName, namespaceName, key, page, size);
        // TODO: test validations
    }

    /**
     * 查询收藏(new added)
     *
     * GET /openapi/v1/favorites
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findFavoritesTest() throws ApiException {
        String userId = null;
        String appId = null;
        Integer page = null;
        Integer size = null;
        List<Object> response = api.findFavorites(userId, appId, page, size);
        // TODO: test validations
    }

    /**
     * 查询命名空间发布历史(new added)
     *
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/releases/histories
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findReleaseHistoriesByNamespaceTest() throws ApiException {
        String appId = null;
        String env = null;
        String clusterName = null;
        String namespaceName = null;
        Integer page = null;
        Integer size = null;
        List<Object> response = api.findReleaseHistoriesByNamespace(appId, env, clusterName, namespaceName, page, size);
        // TODO: test validations
    }

    /**
     * 获取审计配置(new added)
     *
     * GET /openapi/v1/apollo/audit/properties
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAuditPropertiesTest() throws ApiException {
        Object response = api.getAuditProperties();
        // TODO: test validations
    }

    /**
     * 查询开放平台消费者列表(new added)
     *
     * GET /openapi/v1/consumers
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConsumerListTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        List<Object> response = api.getConsumerList(page, size);
        // TODO: test validations
    }

    /**
     * 按应用ID查询消费者Token(new added)
     *
     * GET /openapi/v1/consumer-tokens/by-appId
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConsumerTokenByAppIdTest() throws ApiException {
        String appId = null;
        Object response = api.getConsumerTokenByAppId(appId);
        // TODO: test validations
    }

    /**
     * 获取Portal页面配置(new added)
     *
     * GET /openapi/v1/page-settings
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPageSettingsTest() throws ApiException {
        Object response = api.getPageSettings();
        // TODO: test validations
    }

    /**
     * 获取系统信息(new added)
     *
     * GET /openapi/v1/system-info
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSystemInfoTest() throws ApiException {
        Object response = api.getSystemInfo();
        // TODO: test validations
    }

    /**
     * 导入所有配置(new added)
     *
     * POST /openapi/v1/configs/import
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importAllConfigsTest() throws ApiException {
        String envs = null;
        String conflictAction = null;
        File _file = null;
        api.importAllConfigs(envs, conflictAction, _file);
        // TODO: test validations
    }

    /**
     * 导入应用配置(new added)
     *
     * POST /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/import
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importAppConfigTest() throws ApiException {
        String appId = null;
        String env = null;
        String clusterName = null;
        String conflictAction = null;
        File _file = null;
        api.importAppConfig(appId, env, clusterName, conflictAction, _file);
        // TODO: test validations
    }

    /**
     * 导入配置兼容入口(new added)
     *
     * POST /openapi/v1/import
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importConfigTest() throws ApiException {
        String envs = null;
        String conflictAction = null;
        File _file = null;
        api.importConfig(envs, conflictAction, _file);
        // TODO: test validations
    }

    /**
     * 导入命名空间配置项(new added)
     *
     * POST /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/import
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importNamespaceItemsTest() throws ApiException {
        String appId = null;
        String env = null;
        String clusterName = null;
        String namespaceName = null;
        File _file = null;
        api.importNamespaceItems(appId, env, clusterName, namespaceName, _file);
        // TODO: test validations
    }

    /**
     * 按应用ID或名称搜索应用(new added)
     *
     * GET /openapi/v1/apps/search/by-appid-or-name
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchAppsByAppIdOrNameTest() throws ApiException {
        String query = null;
        Integer page = null;
        Integer size = null;
        Object response = api.searchAppsByAppIdOrName(query, page, size);
        // TODO: test validations
    }

    /**
     * 搜索审计日志(new added)
     *
     * GET /openapi/v1/apollo/audit/logs/by-name-or-type-or-operator
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchAuditLogsTest() throws ApiException {
        String query = null;
        Integer page = null;
        Integer size = null;
        List<Object> response = api.searchAuditLogs(query, page, size);
        // TODO: test validations
    }

    /**
     * 按Key或Value全局搜索配置(new added)
     *
     * GET /openapi/v1/global-search/item-info/by-key-or-value
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchItemInfoByKeyOrValueTest() throws ApiException {
        String key = null;
        String value = null;
        Object response = api.searchItemInfoByKeyOrValue(key, value);
        // TODO: test validations
    }

    /**
     * 收藏置顶(new added)
     *
     * PUT /openapi/v1/favorites/{favoriteId}
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void topFavoriteTest() throws ApiException {
        Long favoriteId = null;
        api.topFavorite(favoriteId);
        // TODO: test validations
    }

}
