/*
 * Apollo OpenAPI
 *
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 *
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OpenConsumerSummaryDto {
    /// 第三方应用ID
    #[serde(rename = "appId", skip_serializing_if = "Option::is_none")]
    pub app_id: Option<String>,
    /// 第三方应用名称
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 部门ID
    #[serde(rename = "orgId", skip_serializing_if = "Option::is_none")]
    pub org_id: Option<String>,
    /// 部门名称
    #[serde(rename = "orgName", skip_serializing_if = "Option::is_none")]
    pub org_name: Option<String>,
    /// 负责人用户名
    #[serde(rename = "ownerName", skip_serializing_if = "Option::is_none")]
    pub owner_name: Option<String>,
    /// 负责人邮箱
    #[serde(rename = "ownerEmail", skip_serializing_if = "Option::is_none")]
    pub owner_email: Option<String>,
    /// Consumer ID
    #[serde(rename = "consumerId", skip_serializing_if = "Option::is_none")]
    pub consumer_id: Option<i64>,
    /// 是否允许该Consumer Token创建应用
    #[serde(rename = "allowCreateApplication", skip_serializing_if = "Option::is_none")]
    pub allow_create_application: Option<bool>,
    /// 是否允许该Consumer Token管理用户
    #[serde(rename = "allowManageUsers", skip_serializing_if = "Option::is_none")]
    pub allow_manage_users: Option<bool>,
    /// 限流QPS，0表示不限流
    #[serde(rename = "rateLimit", skip_serializing_if = "Option::is_none")]
    pub rate_limit: Option<i32>,
    /// 是否开启限流
    #[serde(rename = "rateLimitEnabled", skip_serializing_if = "Option::is_none")]
    pub rate_limit_enabled: Option<bool>,
}

impl OpenConsumerSummaryDto {
    pub fn new() -> OpenConsumerSummaryDto {
        OpenConsumerSummaryDto {
            app_id: None,
            name: None,
            org_id: None,
            org_name: None,
            owner_name: None,
            owner_email: None,
            consumer_id: None,
            allow_create_application: None,
            allow_manage_users: None,
            rate_limit: None,
            rate_limit_enabled: None,
        }
    }
}
