/* tslint:disable */
/* eslint-disable */
/**
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface AddFavoriteRequest {
    body: object;
}

export interface AssignRoleToConsumerRequest {
    token: string;
    type: string;
    body: object;
    envs?: string;
}

export interface CheckExportAppConfigRequest {
    appId: string;
    env: string;
    clusterName: string;
}

export interface CheckSystemHealthRequest {
    instanceId: string;
}

export interface CreateConsumerRequest {
    body: object;
    expires?: string;
}

export interface CreateOrUpdateConfigDBConfigRequest {
    env: string;
    body: object;
}

export interface CreateOrUpdatePortalDBConfigRequest {
    body: object;
}

export interface DeleteConfigDBConfigRequest {
    env: string;
    key: string;
    cluster: string;
}

export interface DeleteConsumerRequest {
    appId: string;
}

export interface DeleteFavoriteRequest {
    favoriteId: number;
}

export interface DeletePortalDBConfigRequest {
    key: string;
}

export interface ExportAllConfigsRequest {
    envs: string;
}

export interface ExportAppConfigRequest {
    appId: string;
    env: string;
    clusterName: string;
}

export interface ExportNamespaceItemsRequest {
    appId: string;
    env: string;
    clusterName: string;
    namespaceName: string;
}

export interface FindAllConfigDBConfigRequest {
    env: string;
}

export interface FindAuditDataInfluencesByFieldRequest {
    entityName: string;
    entityId: string;
    fieldName: string;
    page?: number;
    size?: number;
}

export interface FindAuditLogsRequest {
    page?: number;
    size?: number;
}

export interface FindAuditLogsByOpNameRequest {
    opName: string;
    page?: number;
    size?: number;
    startDate?: string;
    endDate?: string;
}

export interface FindAuditTraceDetailsRequest {
    traceId: string;
}

export interface FindCommitsRequest {
    appId: string;
    env: string;
    clusterName: string;
    namespaceName: string;
    key?: string;
    page?: number;
    size?: number;
}

export interface FindFavoritesRequest {
    userId?: string;
    appId?: string;
    page?: number;
    size?: number;
}

export interface FindReleaseHistoriesByNamespaceRequest {
    appId: string;
    env: string;
    clusterName: string;
    namespaceName: string;
    page?: number;
    size?: number;
}

export interface GetConsumerListRequest {
    page?: number;
    size?: number;
}

export interface GetConsumerTokenByAppIdRequest {
    appId: string;
}

export interface ImportAllConfigsRequest {
    envs: string;
    conflictAction?: string;
    file?: Blob;
}

export interface ImportAppConfigRequest {
    appId: string;
    env: string;
    clusterName: string;
    conflictAction?: string;
    file?: Blob;
}

export interface ImportConfigRequest {
    envs: string;
    conflictAction?: string;
    file?: Blob;
}

export interface ImportNamespaceItemsRequest {
    appId: string;
    env: string;
    clusterName: string;
    namespaceName: string;
    file?: Blob;
}

export interface SearchAppsByAppIdOrNameRequest {
    query?: string;
    page?: number;
    size?: number;
}

export interface SearchAuditLogsRequest {
    query: string;
    page?: number;
    size?: number;
}

export interface SearchItemInfoByKeyOrValueRequest {
    key?: string;
    value?: string;
}

export interface TopFavoriteRequest {
    favoriteId: number;
}

/**
 *
 */
export class PortalManagementApi extends runtime.BaseAPI {

    /**
     * POST /openapi/v1/favorites
     * 添加收藏(new added)
     */
    async addFavoriteRaw(requestParameters: AddFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling addFavorite.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/favorites`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * POST /openapi/v1/favorites
     * 添加收藏(new added)
     */
    async addFavorite(requestParameters: AddFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.addFavoriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * POST /openapi/v1/consumers/{token}/assign-role
     * 给消费者授权(new added)
     */
    async assignRoleToConsumerRaw(requestParameters: AssignRoleToConsumerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        if (requestParameters.token === null || requestParameters.token === undefined) {
            throw new runtime.RequiredError('token','Required parameter requestParameters.token was null or undefined when calling assignRoleToConsumer.');
        }

        if (requestParameters.type === null || requestParameters.type === undefined) {
            throw new runtime.RequiredError('type','Required parameter requestParameters.type was null or undefined when calling assignRoleToConsumer.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling assignRoleToConsumer.');
        }

        const queryParameters: any = {};

        if (requestParameters.type !== undefined) {
            queryParameters['type'] = requestParameters.type;
        }

        if (requestParameters.envs !== undefined) {
            queryParameters['envs'] = requestParameters.envs;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/consumers/{token}/assign-role`.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters.token))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * POST /openapi/v1/consumers/{token}/assign-role
     * 给消费者授权(new added)
     */
    async assignRoleToConsumer(requestParameters: AssignRoleToConsumerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.assignRoleToConsumerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * HEAD /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export
     * 检查应用配置导出权限(new added)
     */
    async checkExportAppConfigRaw(requestParameters: CheckExportAppConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling checkExportAppConfig.');
        }

        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling checkExportAppConfig.');
        }

        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling checkExportAppConfig.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))).replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'HEAD',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * HEAD /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export
     * 检查应用配置导出权限(new added)
     */
    async checkExportAppConfig(requestParameters: CheckExportAppConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.checkExportAppConfigRaw(requestParameters, initOverrides);
    }

    /**
     * GET /openapi/v1/system-info/health
     * 检查系统实例健康状态(new added)
     */
    async checkSystemHealthRaw(requestParameters: CheckSystemHealthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.instanceId === null || requestParameters.instanceId === undefined) {
            throw new runtime.RequiredError('instanceId','Required parameter requestParameters.instanceId was null or undefined when calling checkSystemHealth.');
        }

        const queryParameters: any = {};

        if (requestParameters.instanceId !== undefined) {
            queryParameters['instanceId'] = requestParameters.instanceId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/system-info/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/system-info/health
     * 检查系统实例健康状态(new added)
     */
    async checkSystemHealth(requestParameters: CheckSystemHealthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.checkSystemHealthRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * POST /openapi/v1/consumers
     * 创建开放平台消费者(new added)
     */
    async createConsumerRaw(requestParameters: CreateConsumerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createConsumer.');
        }

        const queryParameters: any = {};

        if (requestParameters.expires !== undefined) {
            queryParameters['expires'] = requestParameters.expires;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/consumers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * POST /openapi/v1/consumers
     * 创建开放平台消费者(new added)
     */
    async createConsumer(requestParameters: CreateConsumerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.createConsumerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * POST /openapi/v1/server/envs/{env}/config-db/config
     * 创建或更新Config DB配置(new added)
     */
    async createOrUpdateConfigDBConfigRaw(requestParameters: CreateOrUpdateConfigDBConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling createOrUpdateConfigDBConfig.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createOrUpdateConfigDBConfig.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/server/envs/{env}/config-db/config`.replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * POST /openapi/v1/server/envs/{env}/config-db/config
     * 创建或更新Config DB配置(new added)
     */
    async createOrUpdateConfigDBConfig(requestParameters: CreateOrUpdateConfigDBConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.createOrUpdateConfigDBConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * POST /openapi/v1/server/portal-db/config
     * 创建或更新Portal DB配置(new added)
     */
    async createOrUpdatePortalDBConfigRaw(requestParameters: CreateOrUpdatePortalDBConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createOrUpdatePortalDBConfig.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/server/portal-db/config`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * POST /openapi/v1/server/portal-db/config
     * 创建或更新Portal DB配置(new added)
     */
    async createOrUpdatePortalDBConfig(requestParameters: CreateOrUpdatePortalDBConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.createOrUpdatePortalDBConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * DELETE /openapi/v1/server/envs/{env}/config-db/config
     * 删除Config DB配置(new added)
     */
    async deleteConfigDBConfigRaw(requestParameters: DeleteConfigDBConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling deleteConfigDBConfig.');
        }

        if (requestParameters.key === null || requestParameters.key === undefined) {
            throw new runtime.RequiredError('key','Required parameter requestParameters.key was null or undefined when calling deleteConfigDBConfig.');
        }

        if (requestParameters.cluster === null || requestParameters.cluster === undefined) {
            throw new runtime.RequiredError('cluster','Required parameter requestParameters.cluster was null or undefined when calling deleteConfigDBConfig.');
        }

        const queryParameters: any = {};

        if (requestParameters.key !== undefined) {
            queryParameters['key'] = requestParameters.key;
        }

        if (requestParameters.cluster !== undefined) {
            queryParameters['cluster'] = requestParameters.cluster;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/server/envs/{env}/config-db/config`.replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * DELETE /openapi/v1/server/envs/{env}/config-db/config
     * 删除Config DB配置(new added)
     */
    async deleteConfigDBConfig(requestParameters: DeleteConfigDBConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConfigDBConfigRaw(requestParameters, initOverrides);
    }

    /**
     * DELETE /openapi/v1/consumers/by-appId
     * 按应用ID删除消费者(new added)
     */
    async deleteConsumerRaw(requestParameters: DeleteConsumerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling deleteConsumer.');
        }

        const queryParameters: any = {};

        if (requestParameters.appId !== undefined) {
            queryParameters['appId'] = requestParameters.appId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/consumers/by-appId`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * DELETE /openapi/v1/consumers/by-appId
     * 按应用ID删除消费者(new added)
     */
    async deleteConsumer(requestParameters: DeleteConsumerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConsumerRaw(requestParameters, initOverrides);
    }

    /**
     * DELETE /openapi/v1/favorites/{favoriteId}
     * 删除收藏(new added)
     */
    async deleteFavoriteRaw(requestParameters: DeleteFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.favoriteId === null || requestParameters.favoriteId === undefined) {
            throw new runtime.RequiredError('favoriteId','Required parameter requestParameters.favoriteId was null or undefined when calling deleteFavorite.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/favorites/{favoriteId}`.replace(`{${"favoriteId"}}`, encodeURIComponent(String(requestParameters.favoriteId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * DELETE /openapi/v1/favorites/{favoriteId}
     * 删除收藏(new added)
     */
    async deleteFavorite(requestParameters: DeleteFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFavoriteRaw(requestParameters, initOverrides);
    }

    /**
     * DELETE /openapi/v1/server/portal-db/config
     * 删除Portal DB配置(new added)
     */
    async deletePortalDBConfigRaw(requestParameters: DeletePortalDBConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.key === null || requestParameters.key === undefined) {
            throw new runtime.RequiredError('key','Required parameter requestParameters.key was null or undefined when calling deletePortalDBConfig.');
        }

        const queryParameters: any = {};

        if (requestParameters.key !== undefined) {
            queryParameters['key'] = requestParameters.key;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/server/portal-db/config`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * DELETE /openapi/v1/server/portal-db/config
     * 删除Portal DB配置(new added)
     */
    async deletePortalDBConfig(requestParameters: DeletePortalDBConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePortalDBConfigRaw(requestParameters, initOverrides);
    }

    /**
     * GET /openapi/v1/configs/export
     * 导出所有配置(new added)
     */
    async exportAllConfigsRaw(requestParameters: ExportAllConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.envs === null || requestParameters.envs === undefined) {
            throw new runtime.RequiredError('envs','Required parameter requestParameters.envs was null or undefined when calling exportAllConfigs.');
        }

        const queryParameters: any = {};

        if (requestParameters.envs !== undefined) {
            queryParameters['envs'] = requestParameters.envs;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/configs/export`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * GET /openapi/v1/configs/export
     * 导出所有配置(new added)
     */
    async exportAllConfigs(requestParameters: ExportAllConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.exportAllConfigsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export
     * 导出应用配置(new added)
     */
    async exportAppConfigRaw(requestParameters: ExportAppConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling exportAppConfig.');
        }

        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling exportAppConfig.');
        }

        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling exportAppConfig.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))).replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/export
     * 导出应用配置(new added)
     */
    async exportAppConfig(requestParameters: ExportAppConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.exportAppConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/export
     * 导出命名空间配置项(new added)
     */
    async exportNamespaceItemsRaw(requestParameters: ExportNamespaceItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling exportNamespaceItems.');
        }

        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling exportNamespaceItems.');
        }

        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling exportNamespaceItems.');
        }

        if (requestParameters.namespaceName === null || requestParameters.namespaceName === undefined) {
            throw new runtime.RequiredError('namespaceName','Required parameter requestParameters.namespaceName was null or undefined when calling exportNamespaceItems.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/export`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))).replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"namespaceName"}}`, encodeURIComponent(String(requestParameters.namespaceName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/export
     * 导出命名空间配置项(new added)
     */
    async exportNamespaceItems(requestParameters: ExportNamespaceItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.exportNamespaceItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/server/envs/{env}/config-db/config/find-all-config
     * 查询指定环境全部Config DB配置(new added)
     */
    async findAllConfigDBConfigRaw(requestParameters: FindAllConfigDBConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling findAllConfigDBConfig.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/server/envs/{env}/config-db/config/find-all-config`.replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/server/envs/{env}/config-db/config/find-all-config
     * 查询指定环境全部Config DB配置(new added)
     */
    async findAllConfigDBConfig(requestParameters: FindAllConfigDBConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.findAllConfigDBConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/server/portal-db/config/find-all-config
     * 查询全部Portal DB配置(new added)
     */
    async findAllPortalDBConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/server/portal-db/config/find-all-config`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/server/portal-db/config/find-all-config
     * 查询全部Portal DB配置(new added)
     */
    async findAllPortalDBConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.findAllPortalDBConfigRaw(initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/apollo/audit/logs/dataInfluences/field
     * 查询审计数据影响(new added)
     */
    async findAuditDataInfluencesByFieldRaw(requestParameters: FindAuditDataInfluencesByFieldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        if (requestParameters.entityName === null || requestParameters.entityName === undefined) {
            throw new runtime.RequiredError('entityName','Required parameter requestParameters.entityName was null or undefined when calling findAuditDataInfluencesByField.');
        }

        if (requestParameters.entityId === null || requestParameters.entityId === undefined) {
            throw new runtime.RequiredError('entityId','Required parameter requestParameters.entityId was null or undefined when calling findAuditDataInfluencesByField.');
        }

        if (requestParameters.fieldName === null || requestParameters.fieldName === undefined) {
            throw new runtime.RequiredError('fieldName','Required parameter requestParameters.fieldName was null or undefined when calling findAuditDataInfluencesByField.');
        }

        const queryParameters: any = {};

        if (requestParameters.entityName !== undefined) {
            queryParameters['entityName'] = requestParameters.entityName;
        }

        if (requestParameters.entityId !== undefined) {
            queryParameters['entityId'] = requestParameters.entityId;
        }

        if (requestParameters.fieldName !== undefined) {
            queryParameters['fieldName'] = requestParameters.fieldName;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apollo/audit/logs/dataInfluences/field`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/apollo/audit/logs/dataInfluences/field
     * 查询审计数据影响(new added)
     */
    async findAuditDataInfluencesByField(requestParameters: FindAuditDataInfluencesByFieldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.findAuditDataInfluencesByFieldRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/apollo/audit/logs
     * 查询审计日志(new added)
     */
    async findAuditLogsRaw(requestParameters: FindAuditLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apollo/audit/logs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/apollo/audit/logs
     * 查询审计日志(new added)
     */
    async findAuditLogs(requestParameters: FindAuditLogsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.findAuditLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/apollo/audit/logs/opName
     * 按操作名查询审计日志(new added)
     */
    async findAuditLogsByOpNameRaw(requestParameters: FindAuditLogsByOpNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        if (requestParameters.opName === null || requestParameters.opName === undefined) {
            throw new runtime.RequiredError('opName','Required parameter requestParameters.opName was null or undefined when calling findAuditLogsByOpName.');
        }

        const queryParameters: any = {};

        if (requestParameters.opName !== undefined) {
            queryParameters['opName'] = requestParameters.opName;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        if (requestParameters.startDate !== undefined) {
            queryParameters['startDate'] = requestParameters.startDate;
        }

        if (requestParameters.endDate !== undefined) {
            queryParameters['endDate'] = requestParameters.endDate;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apollo/audit/logs/opName`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/apollo/audit/logs/opName
     * 按操作名查询审计日志(new added)
     */
    async findAuditLogsByOpName(requestParameters: FindAuditLogsByOpNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.findAuditLogsByOpNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/apollo/audit/trace
     * 查询审计链路详情(new added)
     */
    async findAuditTraceDetailsRaw(requestParameters: FindAuditTraceDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        if (requestParameters.traceId === null || requestParameters.traceId === undefined) {
            throw new runtime.RequiredError('traceId','Required parameter requestParameters.traceId was null or undefined when calling findAuditTraceDetails.');
        }

        const queryParameters: any = {};

        if (requestParameters.traceId !== undefined) {
            queryParameters['traceId'] = requestParameters.traceId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apollo/audit/trace`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/apollo/audit/trace
     * 查询审计链路详情(new added)
     */
    async findAuditTraceDetails(requestParameters: FindAuditTraceDetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.findAuditTraceDetailsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/commits
     * 查询命名空间提交记录(new added)
     */
    async findCommitsRaw(requestParameters: FindCommitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling findCommits.');
        }

        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling findCommits.');
        }

        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling findCommits.');
        }

        if (requestParameters.namespaceName === null || requestParameters.namespaceName === undefined) {
            throw new runtime.RequiredError('namespaceName','Required parameter requestParameters.namespaceName was null or undefined when calling findCommits.');
        }

        const queryParameters: any = {};

        if (requestParameters.key !== undefined) {
            queryParameters['key'] = requestParameters.key;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/commits`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))).replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"namespaceName"}}`, encodeURIComponent(String(requestParameters.namespaceName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/commits
     * 查询命名空间提交记录(new added)
     */
    async findCommits(requestParameters: FindCommitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.findCommitsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/favorites
     * 查询收藏(new added)
     */
    async findFavoritesRaw(requestParameters: FindFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        const queryParameters: any = {};

        if (requestParameters.userId !== undefined) {
            queryParameters['userId'] = requestParameters.userId;
        }

        if (requestParameters.appId !== undefined) {
            queryParameters['appId'] = requestParameters.appId;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/favorites`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/favorites
     * 查询收藏(new added)
     */
    async findFavorites(requestParameters: FindFavoritesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.findFavoritesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/releases/histories
     * 查询命名空间发布历史(new added)
     */
    async findReleaseHistoriesByNamespaceRaw(requestParameters: FindReleaseHistoriesByNamespaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling findReleaseHistoriesByNamespace.');
        }

        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling findReleaseHistoriesByNamespace.');
        }

        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling findReleaseHistoriesByNamespace.');
        }

        if (requestParameters.namespaceName === null || requestParameters.namespaceName === undefined) {
            throw new runtime.RequiredError('namespaceName','Required parameter requestParameters.namespaceName was null or undefined when calling findReleaseHistoriesByNamespace.');
        }

        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/releases/histories`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))).replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"namespaceName"}}`, encodeURIComponent(String(requestParameters.namespaceName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/releases/histories
     * 查询命名空间发布历史(new added)
     */
    async findReleaseHistoriesByNamespace(requestParameters: FindReleaseHistoriesByNamespaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.findReleaseHistoriesByNamespaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/apollo/audit/properties
     * 获取审计配置(new added)
     */
    async getAuditPropertiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apollo/audit/properties`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/apollo/audit/properties
     * 获取审计配置(new added)
     */
    async getAuditProperties(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getAuditPropertiesRaw(initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/consumers
     * 查询开放平台消费者列表(new added)
     */
    async getConsumerListRaw(requestParameters: GetConsumerListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/consumers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/consumers
     * 查询开放平台消费者列表(new added)
     */
    async getConsumerList(requestParameters: GetConsumerListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.getConsumerListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/consumer-tokens/by-appId
     * 按应用ID查询消费者Token(new added)
     */
    async getConsumerTokenByAppIdRaw(requestParameters: GetConsumerTokenByAppIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling getConsumerTokenByAppId.');
        }

        const queryParameters: any = {};

        if (requestParameters.appId !== undefined) {
            queryParameters['appId'] = requestParameters.appId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/consumer-tokens/by-appId`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/consumer-tokens/by-appId
     * 按应用ID查询消费者Token(new added)
     */
    async getConsumerTokenByAppId(requestParameters: GetConsumerTokenByAppIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getConsumerTokenByAppIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/page-settings
     * 获取Portal页面配置(new added)
     */
    async getPageSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/page-settings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/page-settings
     * 获取Portal页面配置(new added)
     */
    async getPageSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getPageSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/system-info
     * 获取系统信息(new added)
     */
    async getSystemInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/system-info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/system-info
     * 获取系统信息(new added)
     */
    async getSystemInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getSystemInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     * POST /openapi/v1/configs/import
     * 导入所有配置(new added)
     */
    async importAllConfigsRaw(requestParameters: ImportAllConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.envs === null || requestParameters.envs === undefined) {
            throw new runtime.RequiredError('envs','Required parameter requestParameters.envs was null or undefined when calling importAllConfigs.');
        }

        const queryParameters: any = {};

        if (requestParameters.envs !== undefined) {
            queryParameters['envs'] = requestParameters.envs;
        }

        if (requestParameters.conflictAction !== undefined) {
            queryParameters['conflictAction'] = requestParameters.conflictAction;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.file !== undefined) {
            formParams.append('file', requestParameters.file as any);
        }

        const response = await this.request({
            path: `/openapi/v1/configs/import`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * POST /openapi/v1/configs/import
     * 导入所有配置(new added)
     */
    async importAllConfigs(requestParameters: ImportAllConfigsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.importAllConfigsRaw(requestParameters, initOverrides);
    }

    /**
     * POST /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/import
     * 导入应用配置(new added)
     */
    async importAppConfigRaw(requestParameters: ImportAppConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling importAppConfig.');
        }

        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling importAppConfig.');
        }

        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling importAppConfig.');
        }

        const queryParameters: any = {};

        if (requestParameters.conflictAction !== undefined) {
            queryParameters['conflictAction'] = requestParameters.conflictAction;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.file !== undefined) {
            formParams.append('file', requestParameters.file as any);
        }

        const response = await this.request({
            path: `/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/import`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))).replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * POST /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/import
     * 导入应用配置(new added)
     */
    async importAppConfig(requestParameters: ImportAppConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.importAppConfigRaw(requestParameters, initOverrides);
    }

    /**
     * POST /openapi/v1/import
     * 导入配置兼容入口(new added)
     */
    async importConfigRaw(requestParameters: ImportConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.envs === null || requestParameters.envs === undefined) {
            throw new runtime.RequiredError('envs','Required parameter requestParameters.envs was null or undefined when calling importConfig.');
        }

        const queryParameters: any = {};

        if (requestParameters.envs !== undefined) {
            queryParameters['envs'] = requestParameters.envs;
        }

        if (requestParameters.conflictAction !== undefined) {
            queryParameters['conflictAction'] = requestParameters.conflictAction;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.file !== undefined) {
            formParams.append('file', requestParameters.file as any);
        }

        const response = await this.request({
            path: `/openapi/v1/import`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * POST /openapi/v1/import
     * 导入配置兼容入口(new added)
     */
    async importConfig(requestParameters: ImportConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.importConfigRaw(requestParameters, initOverrides);
    }

    /**
     * POST /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/import
     * 导入命名空间配置项(new added)
     */
    async importNamespaceItemsRaw(requestParameters: ImportNamespaceItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling importNamespaceItems.');
        }

        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling importNamespaceItems.');
        }

        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling importNamespaceItems.');
        }

        if (requestParameters.namespaceName === null || requestParameters.namespaceName === undefined) {
            throw new runtime.RequiredError('namespaceName','Required parameter requestParameters.namespaceName was null or undefined when calling importNamespaceItems.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.file !== undefined) {
            formParams.append('file', requestParameters.file as any);
        }

        const response = await this.request({
            path: `/openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/import`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))).replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"namespaceName"}}`, encodeURIComponent(String(requestParameters.namespaceName))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * POST /openapi/v1/apps/{appId}/envs/{env}/clusters/{clusterName}/namespaces/{namespaceName}/items/import
     * 导入命名空间配置项(new added)
     */
    async importNamespaceItems(requestParameters: ImportNamespaceItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.importNamespaceItemsRaw(requestParameters, initOverrides);
    }

    /**
     * GET /openapi/v1/apps/search/by-appid-or-name
     * 按应用ID或名称搜索应用(new added)
     */
    async searchAppsByAppIdOrNameRaw(requestParameters: SearchAppsByAppIdOrNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters.query !== undefined) {
            queryParameters['query'] = requestParameters.query;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apps/search/by-appid-or-name`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/apps/search/by-appid-or-name
     * 按应用ID或名称搜索应用(new added)
     */
    async searchAppsByAppIdOrName(requestParameters: SearchAppsByAppIdOrNameRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.searchAppsByAppIdOrNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/apollo/audit/logs/by-name-or-type-or-operator
     * 搜索审计日志(new added)
     */
    async searchAuditLogsRaw(requestParameters: SearchAuditLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        if (requestParameters.query === null || requestParameters.query === undefined) {
            throw new runtime.RequiredError('query','Required parameter requestParameters.query was null or undefined when calling searchAuditLogs.');
        }

        const queryParameters: any = {};

        if (requestParameters.query !== undefined) {
            queryParameters['query'] = requestParameters.query;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apollo/audit/logs/by-name-or-type-or-operator`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/apollo/audit/logs/by-name-or-type-or-operator
     * 搜索审计日志(new added)
     */
    async searchAuditLogs(requestParameters: SearchAuditLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.searchAuditLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/global-search/item-info/by-key-or-value
     * 按Key或Value全局搜索配置(new added)
     */
    async searchItemInfoByKeyOrValueRaw(requestParameters: SearchItemInfoByKeyOrValueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters.key !== undefined) {
            queryParameters['key'] = requestParameters.key;
        }

        if (requestParameters.value !== undefined) {
            queryParameters['value'] = requestParameters.value;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/global-search/item-info/by-key-or-value`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * GET /openapi/v1/global-search/item-info/by-key-or-value
     * 按Key或Value全局搜索配置(new added)
     */
    async searchItemInfoByKeyOrValue(requestParameters: SearchItemInfoByKeyOrValueRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.searchItemInfoByKeyOrValueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * PUT /openapi/v1/favorites/{favoriteId}
     * 收藏置顶(new added)
     */
    async topFavoriteRaw(requestParameters: TopFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.favoriteId === null || requestParameters.favoriteId === undefined) {
            throw new runtime.RequiredError('favoriteId','Required parameter requestParameters.favoriteId was null or undefined when calling topFavorite.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/favorites/{favoriteId}`.replace(`{${"favoriteId"}}`, encodeURIComponent(String(requestParameters.favoriteId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * PUT /openapi/v1/favorites/{favoriteId}
     * 收藏置顶(new added)
     */
    async topFavorite(requestParameters: TopFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.topFavoriteRaw(requestParameters, initOverrides);
    }

}
