/* tslint:disable */
/* eslint-disable */
/**
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExceptionResponse,
  OpenUserDTO,
  OpenUserInfoDTO,
} from '../models';
import {
    ExceptionResponseFromJSON,
    ExceptionResponseToJSON,
    OpenUserDTOFromJSON,
    OpenUserDTOToJSON,
    OpenUserInfoDTOFromJSON,
    OpenUserInfoDTOToJSON,
} from '../models';

export interface ChangeUserEnabledRequest {
    openUserDTO: OpenUserDTO;
}

export interface CreateOrUpdateUserRequest {
    openUserDTO: OpenUserDTO;
    isCreate?: boolean;
}

export interface SearchUsersRequest {
    keyword: string;
    includeInactiveUsers?: boolean;
    offset?: number;
    limit?: number;
}

/**
 *
 */
export class PortalUserManagementApi extends runtime.BaseAPI {

    /**
     * PUT /openapi/v1/users/enabled
     * 修改Portal用户启用状态(new added)
     */
    async changeUserEnabledRaw(requestParameters: ChangeUserEnabledRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.openUserDTO === null || requestParameters.openUserDTO === undefined) {
            throw new runtime.RequiredError('openUserDTO','Required parameter requestParameters.openUserDTO was null or undefined when calling changeUserEnabled.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/users/enabled`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: OpenUserDTOToJSON(requestParameters.openUserDTO),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * PUT /openapi/v1/users/enabled
     * 修改Portal用户启用状态(new added)
     */
    async changeUserEnabled(requestParameters: ChangeUserEnabledRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.changeUserEnabledRaw(requestParameters, initOverrides);
    }

    /**
     * POST /openapi/v1/users
     * 创建或更新Portal用户(new added)
     */
    async createOrUpdateUserRaw(requestParameters: CreateOrUpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.openUserDTO === null || requestParameters.openUserDTO === undefined) {
            throw new runtime.RequiredError('openUserDTO','Required parameter requestParameters.openUserDTO was null or undefined when calling createOrUpdateUser.');
        }

        const queryParameters: any = {};

        if (requestParameters.isCreate !== undefined) {
            queryParameters['isCreate'] = requestParameters.isCreate;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/users`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OpenUserDTOToJSON(requestParameters.openUserDTO),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * POST /openapi/v1/users
     * 创建或更新Portal用户(new added)
     */
    async createOrUpdateUser(requestParameters: CreateOrUpdateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createOrUpdateUserRaw(requestParameters, initOverrides);
    }

    /**
     * GET /openapi/v1/user
     * 获取当前Portal用户(new added)
     */
    async getCurrentUserRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OpenUserInfoDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/user`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OpenUserInfoDTOFromJSON(jsonValue));
    }

    /**
     * GET /openapi/v1/user
     * 获取当前Portal用户(new added)
     */
    async getCurrentUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OpenUserInfoDTO> {
        const response = await this.getCurrentUserRaw(initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/users
     * 搜索Portal用户(new added)
     */
    async searchUsersRaw(requestParameters: SearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OpenUserInfoDTO>>> {
        if (requestParameters.keyword === null || requestParameters.keyword === undefined) {
            throw new runtime.RequiredError('keyword','Required parameter requestParameters.keyword was null or undefined when calling searchUsers.');
        }

        const queryParameters: any = {};

        if (requestParameters.keyword !== undefined) {
            queryParameters['keyword'] = requestParameters.keyword;
        }

        if (requestParameters.includeInactiveUsers !== undefined) {
            queryParameters['includeInactiveUsers'] = requestParameters.includeInactiveUsers;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OpenUserInfoDTOFromJSON));
    }

    /**
     * GET /openapi/v1/users
     * 搜索Portal用户(new added)
     */
    async searchUsers(requestParameters: SearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OpenUserInfoDTO>> {
        const response = await this.searchUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
