# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import apollo_openapi
from apollo_openapi.paths.openapi_v1_consumer_tokens_by_app_id import get  # noqa: E501
from apollo_openapi import configuration, schemas, api_client

from .. import ApiTestMixin


class TestOpenapiV1ConsumerTokensByAppId(ApiTestMixin, unittest.TestCase):
    """
    OpenapiV1ConsumerTokensByAppId unit test stubs
        按应用ID查询消费者Token(new added)  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
